#!/bin/sh
# This is a shell archive (produced by GNU sharutils 4.7).
# To extract the files from this archive, save it to some FILE, remove
# everything before the `#!/bin/sh' line above, then type `sh FILE'.
#
lock_dir=_sh21483
# Made on 2013-04-04 23:50 EDT by <n00692809@osprey.unfcsd.unf.edu>.
# Source directory was `/home/09/n00692809/cop4620/project3'.
#
# Existing files will *not* be overwritten, unless `-c' is specified.
#
# This shar contains:
# length mode       name
# ------ ---------- ------------------------------------------
#    284 -rw-r--r-- ArrayElement.java
#    787 -rw-r--r-- Element.java
#    615 -rw-r--r-- FunElement.java
#   7593 -rw-r--r-- LexicalAnalyzer.java
#     44 -rw-r--r-- makefile
#     28 -rwxrwxr-x p3
#   7163 -rw-r--r-- p3.txt
#  27148 -rw-r--r-- Parser.java
#    782 -rw-r--r-- Semantic.java
#   2023 -rw-r--r-- SymbolTable.java
#  11337 -rw-r--r-- TestFiles.zip
#    340 -rw-r--r-- Token.java
#    274 -rw-r--r-- VarElement.java
#
MD5SUM=${MD5SUM-md5sum}
f=`${MD5SUM} --version | egrep '^md5sum .*(core|text)utils'`
test -n "${f}" && md5check=true || md5check=false
${md5check} || \
  echo 'Note: not verifying md5sums.  Consider installing GNU coreutils.'
save_IFS="${IFS}"
IFS="${IFS}:"
gettext_dir=FAILED
locale_dir=FAILED
first_param="$1"
for dir in $PATH
do
  if test "$gettext_dir" = FAILED && test -f $dir/gettext \
     && ($dir/gettext --version >/dev/null 2>&1)
  then
    case `$dir/gettext --version 2>&1 | sed 1q` in
      *GNU*) gettext_dir=$dir ;;
    esac
  fi
  if test "$locale_dir" = FAILED && test -f $dir/shar \
     && ($dir/shar --print-text-domain-dir >/dev/null 2>&1)
  then
    locale_dir=`$dir/shar --print-text-domain-dir`
  fi
done
IFS="$save_IFS"
if test "$locale_dir" = FAILED || test "$gettext_dir" = FAILED
then
  echo=echo
else
  TEXTDOMAINDIR=$locale_dir
  export TEXTDOMAINDIR
  TEXTDOMAIN=sharutils
  export TEXTDOMAIN
  echo="$gettext_dir/gettext -s"
fi
if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null
then if (echo -n test; echo 1,2,3) | grep n >/dev/null
     then shar_n= shar_c='
'
     else shar_n=-n shar_c= ; fi
else shar_n= shar_c='\c' ; fi
f=shar-touch.$$
st1=200112312359.59
st2=123123592001.59
st2tr=123123592001.5 # old SysV 14-char limit
st3=1231235901

if touch -am -t ${st1} ${f} >/dev/null 2>&1 && \
   test ! -f ${st1} && test -f ${f}; then
  shar_touch='touch -am -t $1$2$3$4$5$6.$7 "$8"'

elif touch -am ${st2} ${f} >/dev/null 2>&1 && \
   test ! -f ${st2} && test ! -f ${st2tr} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$1$2.$7 "$8"'

elif touch -am ${st3} ${f} >/dev/null 2>&1 && \
   test ! -f ${st3} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$2 "$8"'

else
  shar_touch=:
  echo
  ${echo} 'WARNING: not restoring timestamps.  Consider getting and'
  ${echo} 'installing GNU `touch'\'', distributed in GNU coreutils...'
  echo
fi
rm -f ${st1} ${st2} ${st2tr} ${st3} ${f}
#
if test ! -d ${lock_dir}
then : ; else ${echo} 'lock directory '${lock_dir}' exists'
  exit 1
fi
if mkdir ${lock_dir}
then ${echo} 'x - created lock directory `'${lock_dir}\''.'
else ${echo} 'x - failed to create lock directory `'${lock_dir}\''.'
  exit 1
fi
# ============= ArrayElement.java ==============
if test -f 'ArrayElement.java' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING ArrayElement.java (file already exists)'
else
${echo} 'x - extracting ArrayElement.java (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 ArrayElement.java
M+RH)0T]0-#8R,"`M(%!R;VIE8W0@,PT*("H)4W1E<&AE;B!297!P97(-"B`J
M+PT*#0IP=6)L:6,@8VQA<W,@07)R87E%;&5M96YT(&5X=&5N9',@16QE;65N
M=`T*>PT*"7!U8FQI8R!!<G)A>45L96UE;G0H16QE;65N="!E*0T*"7L-"@D)
M;F%M92`](&4N9V5T3F%M92@I.PT*"0ET>7!E(#T@92YG9714>7!E*"D[#0H)
M?0T*"0T*"7!U8FQI8R!!<G)A>45L96UE;G0@8VQO;F4H*0T*"7L-"@D)07)R
M87E%;&5M96YT(&$@/2!N97<@07)R87E%;&5M96YT*'1H:7,I.PT*"0ER971U
X.<FX@83L-"@E]#0I]#0IN
`
end
SHAR_EOF
  (set 20 13 04 04 21 15 26 'ArrayElement.java'; eval "$shar_touch") &&
  chmod 0644 'ArrayElement.java'
if test $? -ne 0
then ${echo} 'restore of ArrayElement.java failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'ArrayElement.java: MD5 check failed'
       ) << \SHAR_EOF
42a0a6e03e13ecc26bcb822f8a3d7e56  ArrayElement.java
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'ArrayElement.java'` -ne 284 && \
  ${echo} 'restoration warning:  size of ArrayElement.java is not 284'
  fi
fi
# ============= Element.java ==============
if test -f 'Element.java' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING Element.java (file already exists)'
else
${echo} 'x - extracting Element.java (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 Element.java
M+RH)0T]0-#8R,"`M(%!R;VIE8W0@,PT*("H)4W1E<&AE;B!297!P97(-"B`J
M+PT*#0IP=6)L:6,@8VQA<W,@16QE;65N="![#0H)<')O=&5C=&5D(%-T<FEN
M9R!N86UE.PT*"7!R;W1E8W1E9"!3=')I;F<@='EP93L-"@EP<F]T96-T960@
M4W1R:6YG('9A;'5E.PT*"0T*"7!U8FQI8R!%;&5M96YT*"D-"@E[#0H)"6YA
M;64@/2!N=6QL.PT*"0ET>7!E(#T@;G5L;#L-"@D)=F%L=64@/2!N=6QL.PT*
M"7T-"@D-"@EP=6)L:6,@16QE;65N="A3=')I;F<@="D-"@E[#0H)"6EF*'0N
M8V]N=&5N=$5Q=6%L<R@B:6YT(BDI#0H)"0ET>7!E(#T@(DY532([#0H)"65L
M<V4@:68H="YC;VYT96YT17%U86QS*")F;&]A="(I*0T*"0D)='EP92`](")&
M3%0B.PT*"0EE;'-E(&EF*'0N8V]N=&5N=$5Q=6%L<R@B=F]I9"(I*0T*"0D)
M='EP92`](")63TE$(CL-"@D)96QS90T*"0D)='EP92`]('0[#0H)?0T*"0T*
M"7!U8FQI8R!V;VED('-E=$YA;64H4W1R:6YG(&XI#0H)>PT*"0EN86UE(#T@
M;CL-"@E]#0H)#0H)<'5B;&EC('9O:60@<V5T5'EP92A3=')I;F<@="D-"@E[
M#0H)"71Y<&4@/2!T.PT*"7T-"@D-"@EP=6)L:6,@=F]I9"!S971686QU92A3
M=')I;F<@=BD-"@E[#0H)"79A;'5E(#T@=CL-"@E]#0H)#0H)<'5B;&EC(%-T
M<FEN9R!G971.86UE*"D-"@E[#0H)"7)E='5R;B!N86UE.PT*"7T-"@D-"@EP
M=6)L:6,@4W1R:6YG(&=E=%1Y<&4H*0T*"7L-"@D)<F5T=7)N('1Y<&4[#0H)
M?0T*"0T*"7!U8FQI8R!%;&5M96YT(&-L;VYE*"D-"@E[#0H)"7)E='5R;B!N
697<@16QE;65N="@I.PT*"7T-"GT-"F-L
`
end
SHAR_EOF
  (set 20 13 04 04 21 21 56 'Element.java'; eval "$shar_touch") &&
  chmod 0644 'Element.java'
if test $? -ne 0
then ${echo} 'restore of Element.java failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'Element.java: MD5 check failed'
       ) << \SHAR_EOF
cc11a5d54e2087dc2e63adffa853d62d  Element.java
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'Element.java'` -ne 787 && \
  ${echo} 'restoration warning:  size of Element.java is not 787'
  fi
fi
# ============= FunElement.java ==============
if test -f 'FunElement.java' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING FunElement.java (file already exists)'
else
${echo} 'x - extracting FunElement.java (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 FunElement.java
M+RH)0T]0-#8R,"`M(%!R;VIE8W0@,PT*("H)4W1E<&AE;B!297!P97(-"B`J
M+PT*#0II;7!O<G0@:F%V82YU=&EL+E9E8W1O<CL-"@T*<'5B;&EC(&-L87-S
M($9U;D5L96UE;G0@97AT96YD<R!%;&5M96YT#0I[#0H)<')I=F%T92!696-T
M;W(\16QE;65N=#X@<&%R86US.PT*"0T*"7!U8FQI8R!&=6Y%;&5M96YT*$5L
M96UE;G0@92D-"@E[#0H)"6YA;64@/2!E+F=E=$YA;64H*3L-"@D)='EP92`]
M(&4N9V5T5'EP92@I.PT*"0EP87)A;7,@/2!N97<@5F5C=&]R/$5L96UE;G0^
M*"D[#0H)?0T*"0T*"7!U8FQI8R!&=6Y%;&5M96YT*%-T<FEN9R!N+"!3=')I
M;F<@="D-"@E[#0H)"6YA;64@/2!N.PT*"0ET>7!E(#T@=#L-"@D)<&%R86US
M(#T@;F5W(%9E8W1O<CQ%;&5M96YT/B@I.PT*"7T-"@D-"@EP=6)L:6,@=F]I
M9"!A9&1087)A;2A%;&5M96YT('`I#0H)>PT*"0EP87)A;7,N861D*'`I.PT*
M"7T-"@D-"@EP=6)L:6,@5F5C=&]R/$5L96UE;G0^(&=E=%!A<F%M<R@I#0H)
M>PT*"0ER971U<FX@<&%R86US.PT*"7T-"@D-"@EP=6)L:6,@1G5N16QE;65N
M="!C;&]N92@I#0H)>PT*"0E&=6Y%;&5M96YT(&8@/2!N97<@1G5N16QE;65N
>="AT:&ES*3L-"@D)<F5T=7)N(&8[#0H)?0T*?0T*
`
end
SHAR_EOF
  (set 20 13 04 04 21 21 33 'FunElement.java'; eval "$shar_touch") &&
  chmod 0644 'FunElement.java'
if test $? -ne 0
then ${echo} 'restore of FunElement.java failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'FunElement.java: MD5 check failed'
       ) << \SHAR_EOF
52e05d9ecb00ed5ba621327456f5bfa4  FunElement.java
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'FunElement.java'` -ne 615 && \
  ${echo} 'restoration warning:  size of FunElement.java is not 615'
  fi
fi
# ============= LexicalAnalyzer.java ==============
if test -f 'LexicalAnalyzer.java' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING LexicalAnalyzer.java (file already exists)'
else
${echo} 'x - extracting LexicalAnalyzer.java (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 LexicalAnalyzer.java
M+RH)0T]0-#8R,"`M(%!R;VIE8W0@,0T*("H)4W1E<&AE;B!297!P97(-"B`J
M+PT*#0II;7!O<G0@:F%V82YI;RY&:6QE.PT*:6UP;W)T(&IA=F$N=71I;"Y3
M8V%N;F5R.PT*:6UP;W)T(&IA=F$N=71I;"Y696-T;W([#0H-"G!U8FQI8R!C
M;&%S<R!,97AI8V%L06YA;'EZ97(@>PT*"0T*"6EN="!C;VUM96YT3&%Y97(@
M/2`P.PT*"6)O;VQE86X@<W!E8U-Y;2`](&9A;'-E.PT*"59E8W1O<CQ4;VME
M;CX@=&]K96YS/2!N97<@5F5C=&]R/%1O:V5N/B@I.PT*"49I;&4@9FEL93L-
M"@E38V%N;F5R(&EN<'5T.PT*"5-T<FEN9R!S<&5C:6%L4WEM8F]L<UM=(#T@
M>R(K(BP@(BTB+"`B/"(L("(^(BP@(CTB+"`B.R(L("(L(BP@(B@B+"`B*2(L
M(`T*"0D)"0D)"2);(BP@(ETB+"`B>R(L(")](BP@(B$B+"`B+R(L("(J(GT[
M#0H)#0H-"@T*"7!U8FQI8R!,97AI8V%L06YA;'EZ97(H1FEL92!F*2!T:')O
M=W,@17AC97!T:6]N#0H)>PT*"0EF:6QE(#T@9CL-"@D)"0D)"0T*"0DO+V9I
M;&4@<F5A9"!F86EL#0H)"6EF("@A*&9I;&4N:7-&:6QE*"D@)B8@9FEL92YC
M86Y296%D*"DI*0T*"0E["5-Y<W1E;2YO=70N<')I;G1L;B@B17)R;W(Z("(@
M*R!F:6QE+F=E=$YA;64H*2`K(`T*"0D)(B!C86YN;W0@8F4@<F5A9"XB*3L-
M"@D)"5-Y<W1E;2YE>&ET*#$I.PT*"0E]#0H)"0D-"@D):6YP=70@/2!N97<@
M4V-A;FYE<BAF:6QE*3L-"@E]#0H-"@DO+W)E=')I979E<R!N97AT('1O:V5N
M(&9R;VT@5F5C=&]R#0H)<'5B;&EC(%1O:V5N(&=E=$YE>'14;VME;B@I#0H)
M>PT*"0E4;VME;B!R971U<FY4;VME;CL-"@D)=VAI;&4H=&]K96YS+FES16UP
M='DH*2D-"@D)>PT*"0D):68H(6=E=$UO<F54;VME;G,H*2D-"@D)"7L-"@D)
M"0ER971U<FY4;VME;B`](&YE=R!4;VME;B@B)"(L(")%3D1/1D9)3$4B*3L-
M"@D)"0ER971U<FX@<F5T=7)N5&]K96X[#0H)"0E]#0H)"7T-"@D)#0H)"7)E
M='5R;E1O:V5N(#T@=&]K96YS+F=E="@P*3L-"@D)=&]K96YS+G)E;6]V92@P
M*3L-"@D)<F5T=7)N(')E='5R;E1O:V5N.PT*"7T-"@D-"@DO+V9I;&QS(%1O
M:V5N(%9E8W1O<B!W:71H(&YE>'0@;&EN92!F<F]M(&9I;&4-"@EP<FEV871E
M(&)O;VQE86X@9V5T36]R951O:V5N<R@I#0H)>PT*"0EW:&EL92AT;VME;G,N
M:7-%;7!T>2@I*0T*"0E[#0H)"0EI9BAI;G!U="YH87-.97AT3&EN92@I*0T*
M"0D)"6%N86QY>F4H:6YP=70N;F5X=$QI;F4H*2YT<FEM*"DI.PT*"0D)96QS
M90T*"0D)"7)E='5R;B!F86QS93L-"@D)?0T*"0D-"@D)<F5T=7)N('1R=64[
M"0D)#0H)?0T*"0T*"2\O86YA;'EZ97,@;F5X="!F:6QE(&QI;F4@=&\@97AT
M<F%C="!T;VME;G,-"@EP<FEV871E('9O:60@86YA;'EZ92A3=')I;F<@<RD-
M"@E[#0H)"2!I9BAS+FQE;F=T:"@I(#T](#`I#0H)"0D@<F5T=7)N.PT*"0D@
M#0H)"2!3>7-T96TN;W5T+G!R:6YT;&XH(DE.4%54.B`@(B`K(',I.PT*"0D@
M#0H)"2!I;G0@<U!O<R`](#`[#0H)"2`-"@D)("\O9F]R(&5V97)Y('!O<VET
M:6]N(&EN('1H92!F:6QE(&QI;F4-"@D)('=H:6QE*'-0;W,@/"!S+FQE;F=T
M:"@I*0T*"0D@>PT*"0D)(%-T<FEN9R!T;VME;B`]("(B.PT*"0D)(`T*"0D)
M("\O<VMI<"!W:&ET97-P86-E#0H)"0D@:68H0VAA<F%C=&5R+FES5VAI=&5S
M<&%C92AS+F-H87)!="AS4&]S*2DI#0H)"0D@>PT*"0D)"2!S4&]S*RL[#0H)
M"0D)(&-O;G1I;G5E.PT*"0D)('T-"@D)"2`O+V-A=&-H(&QI;F4@8V]M;65N
M=',@86YD(&)L;V-K(&-O;6UE;G0@;W!E;FEN9W,-"@D)"2!E;'-E(&EF*',N
M8VAA<D%T*'-0;W,I(#T]("<O)RD-"@D)"2![#0H)"0D)("\O:68@;&EN92!C
M;VUM96YT+"!S:VEP(')E;6%I;F1E<B!O9B!L:6YE#0H)"0D)(&EF*'-0;W,@
M*R`Q(#P@<RYL96YG=&@H*2`F)B!S+F-H87)!="AS4&]S*R`Q*2`]/2`G+R<I
M#0H)"0D)"2!B<F5A:SL-"@D)"0D@+R]I9B!B;&]C:R!C;VUM96YT+"!I;F-R
M96UE;G0@8V]M;65N=$QA>65R("8@<VMI<"`G*B<@8VAA<@T*"0D)"2!E;'-E
M(&EF*'-0;W,@*R`Q(#P@<RYL96YG=&@H*2`F)B!S+F-H87)!="AS4&]S*R`Q
M*2`]/2`G*B<I#0H)"0D)('L-"@D)"0D)(&-O;6UE;G1,87EE<BLK.PT*"0D)
M"0D@<U!O<R`K/2`R.PT*"0D)"2!]#0H)"0D)("\O;&]N92`G+R<@8VAA<F%C
M=&5R("T@861D('1O('1O:V5N#0H)"0D)(&5L<V4-"@D)"0D@>PT*"0D)"0D@
M<W!E8U-Y;2`]('1R=64[#0H)"0D)"2!T;VME;B`]('1O:V5N("L@<RYC:&%R
M070H<U!O<RLK*3L-"@D)"0D@?0T*"0D)('T-"@D)"2`O+V-A=&-H(&-L;W-I
M;F<@8FQO8VL@8V]M;65N=',-"@D)"2!E;'-E(&EF*',N8VAA<D%T*'-0;W,I
M(#T]("<J)RD-"@D)"2![#0H)"0D)("\O:68@;F5X="!C:&%R(&ES("<O)RP@
M9&5C<F5M96YT(&-O;6UE;G1,87EE<B`F('-K:7`@)R\G(&-H87(-"@D)"0D@
M:68H<U!O<R`K(#$@/"!S+FQE;F=T:"@I("8F(',N8VAA<D%T*'-0;W,@*R`Q
M*2`]/2`G+R<@)B8@8V]M;65N=$QA>65R(#X@,"D-"@D)"0D@>PT*"0D)"0D@
M8V]M;65N=$QA>65R+2T[#0H)"0D)"2!S4&]S("L](#([#0H)"0D)('T-"@D)
M"0D@+R]L;VYE("<J)R!C:&%R86-T97(@+2!A9&0@=&\@=&]K96X-"@D)"0D@
M96QS90T*"0D)"2![(`T*"0D)"0D@<W!E8U-Y;2`]('1R=64[#0H)"0D)"2!T
M;VME;B`]('1O:V5N("L@<RYC:&%R070H<U!O<RLK*3L-"@D)"0D@?0T*"0D)
M('T-"@D)"2`O+VAA;F1L92!K97EW;W)D<R!A;F0@:61E;G1I9FEE<G,-"@D)
M"2!E;'-E(&EF*$-H87)A8W1E<BYI<TQE='1E<BAS+F-H87)!="AS4&]S*2DI
M#0H)"0D@>PT*"0D)"2!T;VME;B`]('1O:V5N("L@<RYC:&%R070H<U!O<RLK
M*3L-"@D)"0D@#0H)"0D)("\O=VAI;&4@;F5X="!C:&%R86-T97(@:7,@82!L
M971T97(-"@D)"0D@=VAI;&4H<U!O<R`\(',N;&5N9W1H*"D@)B8@0VAA<F%C
M=&5R+FES3&5T=&5R*',N8VAA<D%T*'-0;W,I*2D-"@D)"0D@>PT*"0D)"0D@
M+R]I9B!N97AT(&-H87(@:7-N)W0@82!L971T97(@;W(@82!S<&5C:6%L('-Y
M;6)O;"P@97)R;W(-"@D)"0D)(&EF*'-0;W,@*R`Q(#P@<RYL96YG=&@H*2`F
M)@T*"0D)"0D)(4-H87)A8W1E<BYI<TQE='1E<BAS+F-H87)!="AS4&]S("L@
M,2DI("8F(`T*"0D)"0D)(4-H87)A8W1E<BYI<U=H:71E<W!A8V4H<RYC:&%R
M070H<U!O<R`K(#$I*2`F)@T*"0D)"0D)(6ES4W!E8VEA;%-Y;6)O;"A#:&%R
M86-T97(N=&]3=')I;F<H<RYC:&%R070H<U!O<R`K(#$I*2DI#0H)"0D)"2![
M#0H)"0D)"0D@=&]K96X@/2!T;VME;B`K(',N8VAA<D%T*'-0;W,K*RD[#0H)
M"0D)"0D@=VAI;&4H<U!O<R`\(',N;&5N9W1H*"D@)B8-"@D)"0D)"0DA0VAA
M<F%C=&5R+FES5VAI=&5S<&%C92AS+F-H87)!="AS4&]S*2D@)B8-"@D)"0D)
M"0DA:7-3<&5C:6%L4WEM8F]L*$-H87)A8W1E<BYT;U-T<FEN9RAS+F-H87)!
M="AS4&]S*2DI*0T*"0D)"0D)('L-"@D)"0D)"0D@=&]K96X@/2!T;VME;B`K
M(',N8VAA<D%T*'-0;W,K*RD[#0H)"0D)"0D@?0T*"0D)"0D)(&)R96%K.PT*
M"0D)"0D@?0T*"0D)"0D@+R]I9B!T;VME;B!H87,@."!C:&%R86-T97)S+"!S
M:VEP(')E;6%I;FEN9R!C:&%R86-T97)S#0H)"0D)"2!I9BAT;VME;BYL96YG
M=&@H*2`]/2`X*0T*"0D)"0D@>PT*"0D)"0D)('=H:6QE*'-0;W,@*R`Q(#P@
M<RYL96YG=&@H*2`F)B`-"@D)"0D)"0D)($-H87)A8W1E<BYI<TQE='1E<BAS
M+F-H87)!="@K*W-0;W,I*2D-"@D)"0D)"0D@.PT*"0D)"0D)(&)R96%K.PT*
M"0D)"0D@?0T*"0D)"0D@=&]K96X@/2!T;VME;B`K(',N8VAA<D%T*'-0;W,K
M*RD[#0H)"0D)('T-"@D)"2!]#0H)"0D@+R]H86YD;&4@:6YT96=E<G,@86YD
M(&9L;V%T<PT*"0D)(&5L<V4@:68H0VAA<F%C=&5R+FES1&EG:70H<RYC:&%R
M070H<U!O<RDI*0T*"0D)('L-"@D)"0D@=&]K96X@/2!T;VME;B`K(',N8VAA
M<D%T*'-0;W,K*RD[#0H)"0D)(`T*"0D)"2`O+V%D9"!D:6=I=',@=&\@=&]K
M96X@=VAI;&4@=&AE>2!R96UA:6X-"@D)"0D@=VAI;&4H<U!O<R`\(',N;&5N
M9W1H*"D@)B8@0VAA<F%C=&5R+FES1&EG:70H<RYC:&%R070H<U!O<RDI*0T*
M"0D)"2![#0H)"0D)"2!T;VME;B`]('1O:V5N("L@<RYC:&%R070H<U!O<RLK
M*3L-"@D)"0D@?0T*"0D)"2`O+V1E=&5C="!D96-I;6%L('!O:6YT#0H)"0D)
M(&EF*'-0;W,@/"!S+FQE;F=T:"@I("8F(',N8VAA<D%T*'-0;W,I(#T]("<N
M)RD-"@D)"0D@>PT*"0D)"0D@=&]K96X@/2!T;VME;B`K(',N8VAA<D%T*'-0
M;W,K*RD[#0H)"0D)"2`-"@D)"0D)("\O861D(&1I9VET<R!T;R!T;VME;B!W
M:&EL92!T:&5Y(')E;6%I;@T*"0D)"0D@=VAI;&4H<U!O<R`\(',N;&5N9W1H
M*"D@)B8-"@D)"0D)"2`@($-H87)A8W1E<BYI<T1I9VET*',N8VAA<D%T*'-0
M;W,I*2D-"@D)"0D)('L-"@D)"0D)"2!T;VME;B`]('1O:V5N("L@<RYC:&%R
M070H<U!O<RLK*3L-"@D)"0D)('T-"@D)"0D@?0T*"0D)"2`O+V1E=&5C="`G
M12<@)B!A9&0@=&\@=&]K96X-"@D)"0D@:68H<U!O<R`\(',N;&5N9W1H*"D@
M)B8@<RYC:&%R070H<U!O<RD@/3T@)T4G*0T*"0D)"2![#0H)"0D)"2!T;VME
M;B`]('1O:V5N("L@<RYC:&%R070H<U!O<RLK*3L-"@D)"0D)("\O:68@;F5X
M="!C:&%R(&ES("<K)R!O<B`G+2<L(&%D9"!T;R!T;VME;@T*"0D)"0D@:68H
M<U!O<R`\(',N;&5N9W1H*"D@)B8@*',N8VAA<D%T*'-0;W,I(#T]("<K)R!\
M?`T*"0D)"0D)<RYC:&%R070H<U!O<RD@/3T@)RTG*2D-"@D)"0D)('L-"@D)
M"0D)"2!T;VME;B`]('1O:V5N("L@<RYC:&%R070H<U!O<RLK*3L-"@D)"0D)
M('T-"@D)"0D)("\O861D(&1I9VET<R!T;R!T;VME;B!W:&EL92!T:&5Y(')E
M;6%I;@T*"0D)"0D@=VAI;&4H<U!O<R`\(',N;&5N9W1H*"D@)B8@#0H)"0D)
M"0D)("`@0VAA<F%C=&5R+FES1&EG:70H<RYC:&%R070H<U!O<RDI*0T*"0D)
M"0D@>PT*"0D)"0D)('1O:V5N(#T@=&]K96X@*R!S+F-H87)!="AS4&]S*RLI
M.PT*"0D)"0D@?0T*"0T*"0D)"2!]#0H)"0D)(`T*"0D)('T-"@D)"2`O+VEF
M(&-H87)A8W1E<B!I<R!S<&5C:6%L('-Y;6)O;"P@861D('1O('1O:V5N(`T*
M"0D)(&5L<V4@:68H:7-3<&5C:6%L4WEM8F]L*$-H87)A8W1E<BYT;U-T<FEN
M9RAS+F-H87)!="AS4&]S*2DI*0T*"0D)('L-"@D)"0D@<W!E8U-Y;2`]('1R
M=64[#0H)"0D)('1O:V5N(#T@=&]K96X@*R!S+F-H87)!="AS4&]S*3L-"@D)
M"0D@#0H)"0D)("\O9&5T96-T('!O=&5N=&EA;"!D;W5B;&4M8VAA<F%C=&5R
M('-Y;6)O;',-"@D)"0D@:68H<RYC:&%R070H<U!O<RD@/3T@)R$G*0T*"0D)
M"2![#0H)"0D)"2!I9B@K*W-0;W,@/"!S+FQE;F=T:"@I("8F(',N8VAA<D%T
M*'-0;W,I(#T]("<])RD-"@D)"0D)"2!T;VME;B`]('1O:V5N("L@<RYC:&%R
M070H<U!O<RLK*3L-"@D)"0D)(&5L<V4-"@D)"0D)"2!S<&5C4WEM(#T@9F%L
M<V4[#0H)"0D)('T-"@D)"0D@96QS92!I9BAS+F-H87)!="AS4&]S*2`]/2`G
M/"<@?'P-"@D)"0D)"2!S+F-H87)!="AS4&]S*2`]/2`G/B<@?'P@<RYC:&%R
M070H<U!O<RD@/3T@)STG*0T*"0D)"2![#0H)"0D)"2!I9B@K*W-0;W,@/"!S
M+FQE;F=T:"@I("8F(',N8VAA<D%T*'-0;W,I(#T]("<])RD-"@D)"0D)"2!T
M;VME;B`]('1O:V5N("L@<RYC:&%R070H<U!O<RLK*3L-"@D)"0D@?0T*"0D)
M"2!E;'-E#0H)"0D)"2!S4&]S*RL[#0H)"0D@?0T*"0D)("\O86YY('5N<F5C
M;V=N:7IE9"!C:&%R<R!A<F4@861D960@=&\@=&]K96X@=&\@8F4@<&%S<V5D
M#0H)"0D@96QS90T*"0D)('L-"@D)"0D@=&]K96X@/2!T;VME;B`K(',N8VAA
M<D%T*'-0;W,K*RD[#0H)"0D)('=H:6QE*'-0;W,@/"!S+FQE;F=T:"@I("8F
M#0H)"0D)"2`@("%#:&%R86-T97(N:7-7:&ET97-P86-E*',N8VAA<D%T*'-0
M;W,I*2`F)@T*"0D)"0D@("`A:7-3<&5C:6%L4WEM8F]L*$-H87)A8W1E<BYT
M;U-T<FEN9RAS+F-H87)!="AS4&]S*2DI*0T*"0D)"2![#0H)"0D)"2!T;VME
M;B`]('1O:V5N("L@<RYC:&%R070H<U!O<RLK*3L-"@D)"0D@?0T*"0D)('T-
M"@D)"2`-"@D)"2!A9&14;VME;BAT;VME;BD[#0H)"2!]#0H)"2`-"@E]#0H)
M#0H)+R]A9&1S(&-U<G)E;G0@=&]K96X@=&\@5&]K96X@5F5C=&]R#0H)<')I
M=F%T92!V;VED(&%D9%1O:V5N*%-T<FEN9R!T;VME;BD-"@E[#0H)"51O:V5N
M('0[#0H)"2\O8VAE8VL@9F]R(&-O;6UE;G0@8FQO8VL-"@D):68H8V]M;65N
M=$QA>65R("$](#`I#0H)"7L-"@D)"6EF*'-P96-3>6TI#0H)"0D)<W!E8U-Y
M;2`](&9A;'-E.PT*"0E]#0H)"2\O=F5R:69Y('1O:V5N(&5X:7-T<PT*"0EE
M;'-E(&EF*'1O:V5N+FQE;F=T:"@I("$](#`I#0H)"7L-"@D)"2`O+VAA;F1L
M92!S<&5C:6%L('-Y;6)O;',-"@D)"2!I9BAS<&5C4WEM*0T*"0D)('L-"@D)
M"0D@="`](&YE=R!4;VME;BAT;VME;BP@(G-Y;6)O;"(I.PT*"0D)"2!T;VME
M;G,N861D*'0I.PT*"0D)"2!S<&5C4WEM(#T@9F%L<V4[#0H)"0D)(')E='5R
M;CL)"0D)#0H)"0D@?0T*"0D)("\O8VAE8VL@=&]K96X@86=A:6YS="!);G1E
M9V5R#0H)"0D@:68H=&]K96XN;6%T8VAE<R@B7%QD*R(I*0T*"0D)('L-"@D)
M"0D@="`](&YE=R!4;VME;BAT;VME;BP@(DY532(I.PT*"0D)"2!T;VME;G,N
M861D*'0I.PT*"0D)('T-"@D)"2`O+V-H96-K('1O:V5N(&%G86EN<W0@1FQO
M870-"@D)"2!E;'-E(&EF*'1O:V5N+FUA=&-H97,H(EQ<9"LH7%PN>S%]7%QD
M*RD_*$5[,7U;*RU=/UQ<9"LI/R(I*0T*"0D)('L-"@D)"0D@="`](&YE=R!4
M;VME;BAT;VME;BP@(D9,5"(I.PT*"0D)"2!T;VME;G,N861D*'0I.PT*"0D)
M('T-"@D)"2`O+V-H96-K(&9O<B!K97EW;W)D<PT*"0D)(&5L<V4@:68H=&]K
M96XN8V]N=&5N=$5Q=6%L<R@B96QS92(I('Q\#0H)"0D)"2!T;VME;BYC;VYT
M96YT17%U86QS*")I9B(I('Q\#0H)"0D)"2!T;VME;BYC;VYT96YT17%U86QS
M*")I;G0B*2!\?`T*"0D)"0D@=&]K96XN8V]N=&5N=$5Q=6%L<R@B<F5T=7)N
M(BD@?'P-"@D)"0D)('1O:V5N+F-O;G1E;G1%<75A;',H(G9O:60B*2!\?`T*
M"0D)"0D@=&]K96XN8V]N=&5N=$5Q=6%L<R@B=VAI;&4B*2D-"@D)"2![#0H)
M"0D)('0@/2!N97<@5&]K96XH=&]K96XL(")K97EW;W)D(BD[#0H)"0D)('1O
M:V5N<RYA9&0H="D[#0H)"0D@?0T*"0D)("\O8VAE8VL@=&]K96X@86=A:6YS
M="!)1`T*"0D)(&5L<V4@:68H=&]K96XN;6%T8VAE<R@B6V$M>D$M6EU[,2PX
M?2(I*0T*"0D)('L-"@D)"0D@="`](&YE=R!4;VME;BAT;VME;BP@(DE$(BD[
M#0H)"0D)('1O:V5N<RYA9&0H="D[#0H)"0D@?0T*"0D)("\O=6YR96-O9VYI
M>F5D('1O:V5N.R!P<FEN="!E<G)O<@T*"0D)(&5L<V4@#0H)"0D@>PT*"0D)
M"2!3>7-T96TN;W5T+G!R:6YT;&XH(D5R<F]R.B`@:6YV86QI9"!T;VME;B`B
M("L@=&]K96XI.PT*"0D)"2!3>7-T96TN97AI="@Q*3L-"@D)"2!]#0H)"2!]
M#0H)?0T*"0T*"2\O9&5T97)M:6YE('=H971H97(@=&]K96X@:7,@<W!E8VEA
M;"!S>6UB;VP-"@EP<FEV871E(&)O;VQE86X@:7-3<&5C:6%L4WEM8F]L*%-T
M<FEN9R!T;VME;BD-"@E[#0H)"69O<BAI;G0@:2`](#`[(&D@/"!S<&5C:6%L
M4WEM8F]L<RYL96YG=&@[(&DK*RD-"@D)('L-"@D)"2!I9BAT;VME;BYC;VYT
M96YT17%U86QS*'-P96-I86Q3>6UB;VQS6VE=*2D-"@D)"0D@<F5T=7)N('1R
A=64[#0H)"2!]#0H)"7)E='5R;B!F86QS93L-"@E]#0I]
`
end
SHAR_EOF
  (set 20 13 04 04 21 10 05 'LexicalAnalyzer.java'; eval "$shar_touch") &&
  chmod 0644 'LexicalAnalyzer.java'
if test $? -ne 0
then ${echo} 'restore of LexicalAnalyzer.java failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'LexicalAnalyzer.java: MD5 check failed'
       ) << \SHAR_EOF
34e4c2bfcde23205039c3211a3602db4  LexicalAnalyzer.java
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'LexicalAnalyzer.java'` -ne 7593 && \
  ${echo} 'restoration warning:  size of LexicalAnalyzer.java is not 7593'
  fi
fi
# ============= makefile ==============
if test -f 'makefile' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING makefile (file already exists)'
else
${echo} 'x - extracting makefile (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'makefile' &&
Semantic.class: Semantic.java
X	javac *.java
SHAR_EOF
  (set 20 13 04 04 22 58 14 'makefile'; eval "$shar_touch") &&
  chmod 0644 'makefile'
if test $? -ne 0
then ${echo} 'restore of makefile failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'makefile: MD5 check failed'
       ) << \SHAR_EOF
8f6ee0334098561fdc3fae5c94e2e30a  makefile
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'makefile'` -ne 44 && \
  ${echo} 'restoration warning:  size of makefile is not 44'
  fi
fi
# ============= p3 ==============
if test -f 'p3' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING p3 (file already exists)'
else
${echo} 'x - extracting p3 (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'p3' &&
#!/bin/ksh
java Semantic $1
SHAR_EOF
  (set 20 13 04 04 22 58 47 'p3'; eval "$shar_touch") &&
  chmod 0775 'p3'
if test $? -ne 0
then ${echo} 'restore of p3 failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'p3: MD5 check failed'
       ) << \SHAR_EOF
9cc9d8a39b63e531515cee13db8cad9b  p3
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'p3'` -ne 28 && \
  ${echo} 'restoration warning:  size of p3 is not 28'
  fi
fi
# ============= p3.txt ==============
if test -f 'p3.txt' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING p3.txt (file already exists)'
else
${echo} 'x - extracting p3.txt (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'p3.txt' &&
Compilers- COP4620
Project 3 - Parser
Stephen Repper
Due:  			4/4/2013
Submission:		4/4/2013
X
X
X
*** Description ***
X
This program takes source code as input and analyzes the input for syntax 
and semantics. The lexical analyzer creates and returns tokens to be parsed and 
semantically analyzed.  Each line of input is echoed to the screen as it is 
processed by the lexical analyzer.  Analysis of each line's syntax and 
semantics takes place after its echo statement, so that if the program fails to 
process the code, the user will know at which line the program failed.  If the 
program successfully processes the code, the program echoes the entire input to 
screen (line-by-line with leading and following spaces trimmed) followed by 
a simple success message: "Complete."  Appropriate error messages are 
displayed upon any error.
X
X
X
*** Running the program ***
X
To compile the source code, enter the following at the prompt:
X	$ make
X
An executable file, p3, is included in the shar file.  to run the program with 
the proper input file, type:
X	$ p3 file.ext
X
where 'file.ext' is the name of the source code with the appropriate extension.
X
The program will execute, and output will be printed to the screen.  No files 
are created by the program.
X
X
X
*** Testing ***
X
Testing was conducted with an extensive batch of .txt and .c files, which have 
been included in a .zip file.  Due to the high volume of test files, log files 
were not created during testing.  All files produced the expected results.
X
X
X
*** Hierarchy ***
X
It should be noted that not every function is elaborated under Parser.java, as 
there is an incredibly large number of functions to reflect the grammar rules.  
Each grammar function follows its logic using if/else statements.
X
[Semantic.java]
main()
X	create a new Semantic object with args[0]
X
Semantic(String arg) - Constructor
X	create a new SymbolTable object
X	create a new File object with arg
X	create a new Parser object with File and SymbolTable
X	set File to null for garbage collection
X	call run() on Parser object
X
X
[Parser.java]
Parser(File file, SymbolTable symtab) - Constructor
X	create new LexicalAnalyzer lex using file
X	Set nextToken to next token from lex
X	set local SymbolTable to symtab
X
run()
X	call first grammar function - program()
X	if main variable is false after run
X		print error
X		call semFail()
X	print success to screen after program() completes
X
parseFail()
X	print "Parse failed."
X	exit program (code 1)
X
semFail()
X	print "Semantic analysis failed."
X	exit program (code 1)
X
Grammar functions
X	A comprehensive list of grammar functions is found at the end of this file.
X
X
[SymbolTable.java]
SymbolTable() - Constructor
X	set elements to new Element array [default size is 53]
X
insert(Element e)
X	call hash(e.getname()) to calculate hashVal
X	set start value to hashVal
X	while the current index of elements is not null
X		if the current element matches e
X			print: Element already exists in table
X			return false (failure)
X		set hashVal to next index (wrapping)
X		if hashVal and start are equal
X			print: Symbol table is full
X			return false (failure)
X	insert e at current index
X	return true (success)
X
lookup(SymbolTable table, String name)
X	set returnElement to null
X	set returnElement to get(table, name)
X	if returnElement is still null
X		print:  Attempt to use undeclared symbol
X	return returnElement
X
get(SymbolTable table, String name)
X	call hash(name) to calculate hashVal
X	set start value to hashVal
X	while current element is not null and element does not match name
X		set hashVal to next index (wrapping)
X		if hashVal and start are equal
X			break
X	if current element is not null and current element matches name
X		return current element
X	else if previous table exists
X		call get(table.prev, name)
X	else
X		return null
X
hash(String s)
X	set returnValue to 0
X	for i = 0 to length of s
X		returnValue = returnValue + 8^(i+1) * s.charAt(i) (mod TableSize)
X	return returnValue
X
addTable()
X	set next to new SymbolTable
X	set next's previous table to this table
X
getNext()
X	return next
X
getPrev()
X	return prev
X
setPrevious(SymbolTable st)
X	set prev to st
X
X
[Element.java]
Element() - Constructor
X	set name, type, and value to null
X
Element(String t)
X	if t is "int"
X		set type to "NUM"
X	else if t is "float"
X		set type to "FLT"
X	else if t is "void"
X		set type to "VOID"
X	else
X		set type to t
X
setName(String n)
X	set name to n
X
setType(String t)
X	set type to t
X
setValue(String v)
X	set value to v
X
getName()
X	return name
X
getType()
X	return type
X
clone()     [Clone exists only for the ability to override]
X	return new Element
X
X
[VarElement.java]  -extends Element
VarElement(Element e) - Constructor
X	set name to e.getName()
X	set type to e.getType()
X
clone()
X	create new VarElement with properties of this object
X	return created VarElement
X
[ArrayElement]  -extends Element
ArrayElement(Element e) - Constructor
X	set name to e.getName()
X	set type to e.getType()
X
clone()
X	create new ArrayElement with properties of this object
X	return created ArrayElement
X
[FunElement.java]  -extends Element
FunElement(Element e)
X	set name to e.getName()
X	set type to e.getType()
X	set params to new Vector<Element>
X
FunElement(String n, String t)
X	set name to n
X	set type to t
X	set params to new Vector<Element>
X
addParam(Element p)
X	call add(p) on params Vector
X
getParams()
X	return params
X
clone()
X	create new FunElement with properties of this object
X	return created FunElement
X
X
[LexicalAnalyzer.java]
LexicalAnalyzer(File f) - Constructor
X	set file to f
X	if file is invalid or can't be read
X		print error and exit program
X	create Scanner (input) to read file
X
getNextToken()
X	while token Vector is empty
X		if getMoreTokens() fails
X			return $ (end of file marker)
X	set returnToken to first token of token Vector
X	remove first token of Vector
X	return returnToken
X
getMoreTokens()
X	while token Vector is empty
X		if input has next line
X			analyze() next line of input
X		else
X			return false
X	return true
X
analyze(String s)
X	This method remains the same as the former implementation of 
X	LexicalAnalyzer.java with the exception of calls to print() being changed
X	to instead call addToken().
X
addToken(String token)
X	This is the former print() method, which has been modified to create a new 
X	Token object for each token found and then add it to a Vector containing 
X	all of the tokens for the current line of input.
X
isSpecialSymbol(String token)
X	This method remains the same as its previous implementation.
X
X
[Token.java]
Token(String tok, String typ) -  Constructor
X	set token to tok
X	set type to typ
X
getToken()
X	return token
X
getType()
X	return type
X
X
GRAMMAR FUNCTIONS (Parser.java):
X	program()
X	decList()
X	decListTwo()
X	dec()
X	decTwo()
X	typeSpec()
X	varDec()
X	funDec()
X	params()
X	paramList()
X	pListTwo()
X	param()
X	paramPost()
X	voidParam()
X	cmpndStmt()
X	localDecs()
X	stmtList()
X	statement()
X	expnStmt()
X	selStmt()
X	selStmtTwo()
X	iterStmt()
X	returnStmt()
X	returnTwo()
X	expression()
X	expressOther()
X	expressID()
X	expressIDTwo()
X	expressIDVar()
X	expressIDCall()
X	var()
X	simpleExpn()
X	relop()
X	addExpn()
X	addExpnTwo()
X	addop()
X	term()
X	termTwo()
X	mulop()
X	factor()
X	factorAlt()
X	iden()
X	call()
X	args()
X	argList()
X	argListTwo()
SHAR_EOF
  (set 20 13 04 04 22 56 19 'p3.txt'; eval "$shar_touch") &&
  chmod 0644 'p3.txt'
if test $? -ne 0
then ${echo} 'restore of p3.txt failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'p3.txt: MD5 check failed'
       ) << \SHAR_EOF
5eba2d3141855385efe776dcd67dd56e  p3.txt
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'p3.txt'` -ne 7163 && \
  ${echo} 'restoration warning:  size of p3.txt is not 7163'
  fi
fi
# ============= Parser.java ==============
if test -f 'Parser.java' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING Parser.java (file already exists)'
else
${echo} 'x - extracting Parser.java (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 Parser.java
M+RH)0T]0-#8R,"`M(%!R;VIE8W0@,PT*("H)4W1E<&AE;B!297!P97(-"B`J
M#0H@*@EM86EN*"D@:&%S(&)E96X@;6]V960@=&\@4V5M86YT:6,N:F%V82!F
M;W(@4')O:F5C="`S#0H@*B\-"@T*#0II;7!O<G0@:F%V82YI;RY&:6QE.PT*
M#0IP=6)L:6,@8VQA<W,@4&%R<V5R#0I[#0H)3&5X:6-A;$%N86QY>F5R(&QE
M>#L-"@E4;VME;B!N97AT5&]K96X[#0H)4WEM8F]L5&%B;&4@<W0[#0H)1G5N
M16QE;65N="!F=6YC.PT*"45L96UE;G0@93L-"@EB;V]L96%N(&UA:6X@/2!F
M86QS93L-"@D-"@DO*@E#;VYS=')U8W1O<B!C86QL<R!,97AI8V%L06YA;'EZ
M97(@9F]R('1H92!F:7)S="!T;VME;B!F<F]M('1H92!F:6QE+@T*"2`J+PT*
M"7!U8FQI8R!087)S97(H1FEL92!F:6QE+"!3>6UB;VQ486)L92!S>6UT86(I
M('1H<F]W<R!%>&-E<'1I;VX-"@E[#0H)"6QE>"`](&YE=R!,97AI8V%L06YA
M;'EZ97(H9FEL92D[#0H)"6YE>'14;VME;B`](&QE>"YG971.97AT5&]K96XH
M*3L-"@D)<W0@/2!S>6UT86([#0H)?0T*"0T*"2\J"5)U;B!C86QL<R!T:&4@
M9FER<W0@9W)A;6UA<B!R=6QE+B`@268@;F\@97)R;W)S(&]C8W5R(&1U<FEN
M9R!T:&4@<&%R<V4L#0H)("H@"7!R;V=R86TH*2!W:6QL(&-O;7!L971E+"!A
M;F0@<W5C8V5S<R!W:6QL(&)E('!R:6YT960@=&\@<V-R965N+@T*"2`J+PT*
M"7!U8FQI8R!3>6UB;VQ486)L92!R=6XH*0T*"7L-"@D)<')O9W)A;2@I.PT*
M"0EI9B@A;6%I;BD-"@D)>PT*"0D)4WES=&5M+F]U="YP<FEN=&QN*").;R!M
M86EN*"D@:6X@<')O9W)A;2XB*3L-"@D)"7-E;49A:6PH*3L-"@D)?0T*"0E3
M>7-T96TN;W5T+G!R:6YT;&XH(D-O;7!L971E+B(I.PT*"0ER971U<FX@<W0[
M#0H)?0T*"0T*"2\J"4%C8V5P="!C=7)R96YT('1O:V5N(&)Y(&-A;&QI;F<@
M9V5T3F5X=%1O:V5N*"D@9G)O;2!,97AI8V%L06YA;'EZ97(-"@D@*B\-"@EP
M<FEV871E('9O:60@86-C97!T*"D-"@E[#0H)"6YE>'14;VME;B`](&QE>"YG
M971.97AT5&]K96XH*3L-"@E]#0H)#0H)+RH)06QL(&=R86UM87(@9G5N8W1I
M;VYS(&%R92!M97)E;'D@:6UP;&5M96YT871I;VYS(&]F#0H)("H@"71H96ER
M(')E<W!E8W1I=F4@9W)A;6UA<B!A;F0@<V5M86YT:6,@<G5L97,N(`T*"2`J
M+PT*"7!R:79A=&4@=F]I9"!P<F]G<F%M*"D-"@E[#0H)"6EF*&YE>'14;VME
M;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(FEN="(I('Q\#0H)"0D);F5X
M=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B9FQO870B*2!\?`T*
M"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(G9O:60B
M*2D-"@D)"61E8TQI<W0H*3L-"@D)96QS90T*"0D)<&%R<V5&86EL*"D[#0H)
M?0T*"0T*"7!R:79A=&4@=F]I9"!D96-,:7-T*"D-"@E[#0H)"6EF*&YE>'14
M;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(FEN="(I('Q\#0H)"0EN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")F;&]A="(I('Q\
M#0H)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")V;VED
M(BDI#0H)"7L-"@D)"61E8R@I.PT*"0D)9&5C3&ES=%1W;R@I.PT*"0E]#0H)
M"65L<V4-"@D)"7!A<G-E1F%I;"@I.PT*"7T-"@D-"@EP<FEV871E('9O:60@
M9&5C3&ES=%1W;R@I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T5&]K96XH*2YC
M;VYT96YT17%U86QS*")I;G0B*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME
M;B@I+F-O;G1E;G1%<75A;',H(F9L;V%T(BD@?'P-"@D)"0EN97AT5&]K96XN
M9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")V;VED(BDI#0H)"7L-"@D)"61E
M8R@I.PT*"0D)9&5C3&ES=%1W;R@I.PT*"0E]#0H)"65L<V4@:68H(6YE>'14
M;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(B0B*2D-"@D)"7!A<G-E
M1F%I;"@I.PT*"7T-"@D-"@EP<FEV871E('9O:60@9&5C*"D-"@E[#0H)"6EF
M*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(FEN="(I('Q\
M#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B9FQO
M870B*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A
M;',H(G9O:60B*2D-"@D)>PT*"0D)='EP95-P96,H*3L-"@D)"6EF*&YE>'14
M;VME;BYG9714>7!E*"DN8V]N=&5N=$5Q=6%L<R@B240B*2D-"@D)"7L-"@D)
M"0EE+G-E=$YA;64H;F5X=%1O:V5N+F=E=%1O:V5N*"DI.PT*"0D)"6%C8V5P
M="@I.PT*"0D)?0T*"0D)96QS90T*"0D)"7!A<G-E1F%I;"@I.PT*"0D)9&5C
M5'=O*"D[#0H)"7T-"@D)96QS92`-"@D)"7!A<G-E1F%I;"@I.PT*"7T-"@D-
M"@EP<FEV871E('9O:60@9&5C5'=O*"D-"@E[#0H)"6EF*&YE>'14;VME;BYG
M9714;VME;B@I+F-O;G1E;G1%<75A;',H(B@B*2D-"@D)>PT*"0D)9G5N1&5C
M*"D[#0H)"7T-"@D)96QS92!I9BAN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT
M96YT17%U86QS*");(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC
M;VYT96YT17%U86QS*"([(BDI#0H)"0EV87)$96,H*3L-"@D)96QS90T*"0D)
M<&%R<V5&86EL*"D[#0H)?0T*"0T*"7!R:79A=&4@=F]I9"!T>7!E4W!E8R@I
M#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS
M*")I;G0B*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%
M<75A;',H(F9L;V%T(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC
M;VYT96YT17%U86QS*")V;VED(BDI#0H)"7L-"@D)"64@/2!N97<@16QE;65N
M="AN97AT5&]K96XN9V5T5&]K96XH*2D[#0H)"0EA8V-E<'0H*3L-"@D)?0T*
M"7T-"@D-"@EP<FEV871E('9O:60@=F%R1&5C*"D-"@E[#0H)"6EF*&4N9V5T
M5'EP92@I+F-O;G1E;G1%<75A;',H(E9/240B*2D-"@D)>PT*"0D)4WES=&5M
M+F]U="YP<FEN=&QN*")687)I86)L92!C86YN;W0@8F4@='EP92!V;VED+B(I
M.PT*"0D)<V5M1F%I;"@I.PT*"0E]#0H)"6EF*&YE>'14;VME;BYG9714;VME
M;B@I+F-O;G1E;G1%<75A;',H(ELB*2D-"@D)>PT*"0D)07)R87E%;&5M96YT
M(&$@/2!N97<@07)R87E%;&5M96YT*&4I.PT*"0D)82YS971686QU92@B,"(I
M.PT*"0D)92`](&YU;&P[#0H)"0EA8V-E<'0H*3L-"@D)"6EF*&YE>'14;VME
M;BYG9714>7!E*"DN8V]N=&5N=$5Q=6%L<R@B3E5-(BDI#0H)"0E[#0H)"0D)
M86-C97!T*"D[#0H)"0D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N
M=$5Q=6%L<R@B72(I*0T*"0D)"7L-"@D)"0D)86-C97!T*"D[#0H)"0D)"6EF
M*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(CLB*2D-"@D)
M"0D)>PT*"0D)"0D):68H(7-T+FEN<V5R="AA*2D-"@D)"0D)"0ES96U&86EL
M*"D[#0H)"0D)"0EA8V-E<'0H*3L-"@D)"0D)?0T*"0D)"0EE;'-E#0H)"0D)
M"0EP87)S949A:6PH*3L-"@D)"0E]#0H)"0D)96QS90T*"0D)"0EP87)S949A
M:6PH*3L-"@D)"7T-"@D)"65L<V4-"@D)"0EP87)S949A:6PH*3L-"@D)?0T*
M"0EE;'-E(&EF*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H
M(CLB*2D-"@D)>PT*"0D)5F%R16QE;65N="!V(#T@;F5W(%9A<D5L96UE;G0H
M92D[#0H)"0EE(#T@;G5L;#L-"@D)"6EF*"%S="YI;G-E<G0H=BDI#0H)"0D)
M<V5M1F%I;"@I.PT*"0D)86-C97!T*"D[#0H)"7T-"@D)96QS90T*"0D)<&%R
M<V5&86EL*"D[#0H)?0T*"0T*"7!R:79A=&4@=F]I9"!F=6Y$96,H*0T*"7L-
M"@D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B*"(I
M*0T*"0E[#0H)"0EB;V]L96%N(')E="`](&9A;'-E.PT*"0D)9G5N8R`](&YE
M=R!&=6Y%;&5M96YT*&4I.PT*"0D)92`](&YU;&P[#0H)"0EA8V-E<'0H*3L-
M"@D)"6EF*&UA:6X@/3T@=')U92D-"@D)"7L-"@D)"0E3>7-T96TN;W5T+G!R
M:6YT;&XH(FUA:6XH*2!I<R!N;W0@;&%S="!F=6YC=&EO;B!D96-L87)E9"XB
M*3L-"@D)"0ES96U&86EL*"D[#0H)"0E]#0H)"0EE;'-E(&EF*&9U;F,N9V5T
M3F%M92@I+F-O;G1E;G1%<75A;',H(FUA:6XB*2D-"@D)"0EM86EN(#T@=')U
M93L-"@D)"0D-"@D)"7-T+F%D9%1A8FQE*"D[#0H)"0EP87)A;7,H*3L-"@D)
M"6EF*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(BDB*2D-
M"@D)"7L-"@D)"0EI9B@A<W0N:6YS97)T*&9U;F,I*0T*"0D)"0ES96U&86EL
M*"D[#0H)"0D)86-C97!T*"D[#0H)"0D)<F5T(#T@8VUP;F13=&UT*')E="D[
M#0H)"0D):68H(2AR970@?'P@<W0N;&]O:W5P*'-T+"!F=6YC+F=E=$YA;64H
M*2DN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(E9/240B*2DI#0H)"0D)>PT*
M"0D)"0E3>7-T96TN;W5T+G!R:6YT;&XH(D9U;F-T:6]N("(@*R!F=6YC+F=E
M=$YA;64H*2`K("(H*2!I<R!N;W0@=F]I9"!T>7!E.R`B("L-"@D)"0D)"0DB
M(&UU<W0@:&%V92!A(')E='5R;BXB*3L-"@D)"0D)<V5M1F%I;"@I.PT*"0D)
M"7T-"@D)"0EF=6YC(#T@;G5L;#L-"@D)"7T-"@D)"65L<V4-"@D)"0EP87)S
M949A:6PH*3L-"@D)?0T*"0EE;'-E#0H)"0EP87)S949A:6PH*3L-"@E]#0H)
M#0H)<')I=F%T92!V;VED('!A<F%M<R@I#0H)>PT*"0EI9BAN97AT5&]K96XN
M9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")I;G0B*2!\?`T*"0D);F5X=%1O
M:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B9FQO870B*2D-"@D)>PT*
M"0D)92`](&YE=R!%;&5M96YT*&YE>'14;VME;BYG9714;VME;B@I*3L-"@D)
M"6%C8V5P="@I.PT*"0D)<&%R86U,:7-T*"D[#0H)"7T-"@D)96QS92!I9BAN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")V;VED(BDI#0H)
M"7L-"@D)"64@/2!N97<@16QE;65N="AN97AT5&]K96XN9V5T5&]K96XH*2D[
M#0H)"0EF=6YC+F%D9%!A<F%M*&4I.PT*"0D)86-C97!T*"D[#0H)"7T-"@D)
M96QS90T*"0D)<&%R<V5&86EL*"D[#0H)?0T*"0T*"7!R:79A=&4@=F]I9"!P
M87)A;4QI<W0H*0T*"7L-"@D):68H;F5X=%1O:V5N+F=E=%1Y<&4H*2YC;VYT
M96YT17%U86QS*"))1"(I*0T*"0E[#0H)"0EE+G-E=$YA;64H;F5X=%1O:V5N
M+F=E=%1O:V5N*"DI.PT*"0D)86-C97!T*"D[#0H)"0EP87)A;5!O<W0H*3L-
M"@D)"7!,:7-T5'=O*"D[#0H)"7T-"@D)96QS90T*"0D)<&%R<V5&86EL*"D[
M#0H)?0T*"0T*"7!R:79A=&4@=F]I9"!P3&ES=%1W;R@I#0H)>PT*"0EI9BAN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(L(BDI#0H)"7L-
M"@D)"6%C8V5P="@I.PT*"0D)<&%R86TH*3L-"@D)"7!,:7-T5'=O*"D[#0H)
M"7T-"@D)96QS92!I9B@A;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q
M=6%L<R@B*2(I*0T*"0D)<&%R<V5&86EL*"D[#0H)?0T*"0T*"7!R:79A=&4@
M=F]I9"!P87)A;2@I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T5&]K96XH*2YC
M;VYT96YT17%U86QS*")I;G0B*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME
M;B@I+F-O;G1E;G1%<75A;',H(F9L;V%T(BDI#0H)"7L-"@D)"64@/2!N97<@
M16QE;65N="AN97AT5&]K96XN9V5T5&]K96XH*2D[#0H)"0EA8V-E<'0H*3L-
M"@D)"6EF*&YE>'14;VME;BYG9714>7!E*"DN8V]N=&5N=$5Q=6%L<R@B240B
M*2D-"@D)"7L-"@D)"0EE+G-E=$YA;64H;F5X=%1O:V5N+F=E=%1O:V5N*"DI
M.PT*"0D)"6%C8V5P="@I.PT*"0D)?0T*"0D)96QS90T*"0D)"7!A<G-E1F%I
M;"@I.PT*"0D)<&%R86U0;W-T*"D[#0H)"7T-"@D)96QS90T*"0D)<&%R<V5&
M86EL*"D[#0H)?0T*"0T*"7!R:79A=&4@=F]I9"!P87)A;5!O<W0H*0T*"7L-
M"@D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B6R(I
M*0T*"0E[#0H)"0EA8V-E<'0H*3L-"@D)"6EF*&YE>'14;VME;BYG9714;VME
M;B@I+F-O;G1E;G1%<75A;',H(ETB*2D-"@D)"7L-"@D)"0E!<G)A>45L96UE
M;G0@82`](&YE=R!!<G)A>45L96UE;G0H92D[#0H)"0D)92`](&YU;&P[#0H)
M"0D)9G5N8RYA9&1087)A;2AA*3L-"@D)"0EI9B@A<W0N9V5T3F5X="@I+FEN
M<V5R="AA*2D-"@D)"0D)<V5M1F%I;"@I.PT*"0D)"6%C8V5P="@I.PT*"0D)
M?0T*"0D)96QS90T*"0D)"7!A<G-E1F%I;"@I.PT*"0E]#0H)"65L<V4@:68H
M;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B*2(I('Q\#0H)
M"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B+"(I*0T*
M"0E[#0H)"0E687)%;&5M96YT('8@/2!N97<@5F%R16QE;65N="AE*3L-"@D)
M"64@/2!N=6QL.PT*"0D)9G5N8RYA9&1087)A;2AV*3L-"@D)"6EF*"%S="YG
M971.97AT*"DN:6YS97)T*'8I*0T*"0D)"7-E;49A:6PH*3L-"@D)?0T*"0EE
M;'-E#0H)"0EP87)S949A:6PH*3L-"@E]#0H)#0H)<')I=F%T92!B;V]L96%N
M(&-M<&YD4W1M="AB;V]L96%N('(I#0H)>PT*"0ES="`]('-T+F=E=$YE>'0H
M*3L-"@D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B
M>R(I*0T*"0E[#0H)"0EA8V-E<'0H*3L-"@D)"6QO8V%L1&5C<R@I.PT*"0D)
M<B`]('-T;71,:7-T*'(I.PT*"0D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN
M8V]N=&5N=$5Q=6%L<R@B?2(I*0T*"0D)>PT*"0D)"7-T(#T@<W0N9V5T4')E
M=B@I.PT*"0D)"6%C8V5P="@I.PT*"0D)?0T*"0D)96QS90T*"0D)"7!A<G-E
M1F%I;"@I.PT*"0D)#0H)"7T-"@D)96QS90T*"0D)<&%R<V5&86EL*"D[#0H)
M"0T*"0ER971U<FX@<CL-"@E]#0H)#0H)<')I=F%T92!V;VED(&QO8V%L1&5C
M<R@I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U
M86QS*")I;G0B*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E
M;G1%<75A;',H(F9L;V%T(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH
M*2YC;VYT96YT17%U86QS*")V;VED(BDI#0H)"7L-"@D)"71Y<&53<&5C*"D[
M#0H)"0EI9BAN97AT5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(DE$
M(BDI#0H)"0E[#0H)"0D)92YS971.86UE*&YE>'14;VME;BYG9714;VME;B@I
M*3L-"@D)"0EA8V-E<'0H*3L-"@D)"7T-"@D)"65L<V4-"@D)"0EP87)S949A
M:6PH*3L-"@D)"79A<D1E8R@I.PT*"0D);&]C86Q$96-S*"D[#0H)"7T-"@D)
M96QS92!I9B@A*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H
M(FEF(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U
M86QS*")W:&EL92(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N
M=&5N=$5Q=6%L<R@B<F5T=7)N(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5'EP
M92@I+F-O;G1E;G1%<75A;',H(DE$(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T
M5'EP92@I+F-O;G1E;G1%<75A;',H(DY532(I('Q\#0H)"0D);F5X=%1O:V5N
M+F=E=%1Y<&4H*2YC;VYT96YT17%U86QS*")&3%0B*2!\?`T*"0D)"6YE>'14
M;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(B@B*2!\?`T*"0D)"6YE
M>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(GLB*2!\?`T*"0D)
M"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(GTB*2!\?`T*
M"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(CLB*2DI
M#0H)"0EP87)S949A:6PH*3L-"@E]#0H)#0H)<')I=F%T92!B;V]L96%N('-T
M;71,:7-T*&)O;VQE86X@<BD-"@E[#0H)"6EF*&YE>'14;VME;BYG9714;VME
M;B@I+F-O;G1E;G1%<75A;',H(FEF(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T
M5&]K96XH*2YC;VYT96YT17%U86QS*")W:&EL92(I('Q\#0H)"0D);F5X=%1O
M:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B<F5T=7)N(BD@?'P-"@D)
M"0EN97AT5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(DE$(BD@?'P-
M"@D)"0EN97AT5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(DY532(I
M('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1Y<&4H*2YC;VYT96YT17%U86QS*")&
M3%0B*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A
M;',H(B@B*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%
M<75A;',H(GLB*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E
M;G1%<75A;',H(CLB*2D-"@D)>PT*"0D)<B`]('-T871E;65N="AR*3L-"@D)
M"7(@/2!S=&UT3&ES="AR*3L-"@D)?0T*"0EE;'-E(&EF*"%N97AT5&]K96XN
M9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")](BDI#0H)"0EP87)S949A:6PH
M*3L-"@D)#0H)"7)E='5R;B!R.PT*"7T-"@D-"@EP<FEV871E(&)O;VQE86X@
M<W1A=&5M96YT*&)O;VQE86X@<BD-"@E[#0H)"6EF*&YE>'14;VME;BYG9714
M;VME;B@I+F-O;G1E;G1%<75A;',H(FEF(BDI#0H)"0ER(#T@<V5L4W1M="AR
M*3L-"@D)96QS92!I9BAN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U
M86QS*")W:&EL92(I*0T*"0D):71E<E-T;70H*3L-"@D)96QS92!I9BAN97AT
M5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")R971U<FXB*2D-"@D)
M"7(@/2!R971U<FY3=&UT*'(I.PT*"0EE;'-E(&EF*&YE>'14;VME;BYG9714
M>7!E*"DN8V]N=&5N=$5Q=6%L<R@B240B*2!\?`T*"0D)"6YE>'14;VME;BYG
M9714>7!E*"DN8V]N=&5N=$5Q=6%L<R@B3E5-(BD@?'P-"@D)"0EN97AT5&]K
M96XN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(D9,5"(I('Q\#0H)"0D);F5X
M=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B*"(I('Q\#0H)"0D)
M;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B.R(I*0T*"0D)
M97AP;E-T;70H*3L-"@D)96QS92!I9BAN97AT5&]K96XN9V5T5&]K96XH*2YC
M;VYT96YT17%U86QS*")[(BDI#0H)"7L-"@D)"7-T+F%D9%1A8FQE*"D[#0H)
M"0EC;7!N9%-T;70H9F%L<V4I.PT*"0E]#0H)"65L<V4-"@D)"7!A<G-E1F%I
M;"@I.PT*"0D-"@D)<F5T=7)N('([#0H)?0T*"0T*"7!R:79A=&4@=F]I9"!E
M>'!N4W1M="@I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T5'EP92@I+F-O;G1E
M;G1%<75A;',H(DE$(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5'EP92@I+F-O
M;G1E;G1%<75A;',H(DY532(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1Y<&4H
M*2YC;VYT96YT17%U86QS*")&3%0B*2!\?`T*"0D)"6YE>'14;VME;BYG9714
M;VME;B@I+F-O;G1E;G1%<75A;',H(B@B*2D-"@D)>PT*"0D)97AP<F5S<VEO
M;B@I.PT*"0D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L
M<R@B.R(I*0T*"0D)"0EA8V-E<'0H*3L-"@D)"65L<V4-"@D)"0EP87)S949A
M:6PH*3L-"@D)?0T*"0EE;'-E(&EF*&YE>'14;VME;BYG9714;VME;B@I+F-O
M;G1E;G1%<75A;',H(CLB*2D-"@D)"6%C8V5P="@I.PT*"0EE;'-E#0H)"0EP
M87)S949A:6PH*3L-"@E]#0H)#0H)<')I=F%T92!B;V]L96%N('-E;%-T;70H
M8F]O;&5A;B!R*0T*"7L-"@D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N
M=&5N=$5Q=6%L<R@B:68B*2D-"@D)>PT*"0D)86-C97!T*"D[#0H)"0EI9BAN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(H(BDI#0H)"0D)
M86-C97!T*"D[#0H)"0EE;'-E#0H)"0D)<&%R<V5&86EL*"D[#0H)"0D-"@D)
M"65X<')E<W-I;VXH*3L-"@D)"0T*"0D):68H;F5X=%1O:V5N+F=E=%1O:V5N
M*"DN8V]N=&5N=$5Q=6%L<R@B*2(I*0T*"0D)"6%C8V5P="@I.PT*"0D)96QS
M90T*"0D)"7!A<G-E1F%I;"@I.PT*"0D)<B`]('-T871E;65N="AR*3L-"@D)
M"7(@/2!S96Q3=&UT5'=O*'(I.PT*"0E]#0H)"65L<V4-"@D)"7!A<G-E1F%I
M;"@I.PT*"0D-"@D)<F5T=7)N('([#0H)?0T*"0T*"7!R:79A=&4@8F]O;&5A
M;B!S96Q3=&UT5'=O*&)O;VQE86X@<BD-"@E[#0H)"6EF*&YE>'14;VME;BYG
M9714;VME;B@I+F-O;G1E;G1%<75A;',H(F5L<V4B*2D-"@D)>PT*"0D)86-C
M97!T*"D[#0H)"0EB;V]L96%N(&(@/2!S=&%T96UE;G0H<BD[#0H)"0EI9B@H
M8B`F)B`A<BD@?'P@*'(@)B8@(6(I*0T*"0D)"7(@/2!F86QS93L-"@D)?0T*
M"0EE;'-E(&EF*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H
M(FEF(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%<75A
M;',H(DE$(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%
M<75A;',H(DY532(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1Y<&4H*2YC;VYT
M96YT17%U86QS*")&3%0B*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I
M+F-O;G1E;G1%<75A;',H(G=H:6QE(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T
M5&]K96XH*2YC;VYT96YT17%U86QS*")R971U<FXB*2!\?`T*"0D)"6YE>'14
M;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(B@B*2!\?`T*"0D)"6YE
M>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(GLB*2!\?`T*"0D)
M"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(GTB*2!\?`T*
M"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(CLB*2D-
M"@D)"3L-"@D)96QS90T*"0D)<&%R<V5&86EL*"D[#0H)"0T*"0ER971U<FX@
M<CL-"@E]#0H)#0H)<')I=F%T92!V;VED(&ET97)3=&UT*"D-"@E[#0H)"6EF
M*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(G=H:6QE(BDI
M#0H)"7L-"@D)"6%C8V5P="@I.PT*"0D):68H;F5X=%1O:V5N+F=E=%1O:V5N
M*"DN8V]N=&5N=$5Q=6%L<R@B*"(I*0T*"0D)"6%C8V5P="@I.PT*"0D)96QS
M90T*"0D)"7!A<G-E1F%I;"@I.PT*"0D)97AP<F5S<VEO;B@I.PT*"0D):68H
M;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B*2(I*0T*"0D)
M"6%C8V5P="@I.PT*"0D)96QS90T*"0D)"7!A<G-E1F%I;"@I.PT*"0D)<W1A
M=&5M96YT*&9A;'-E*3L-"@D)?0T*"0EE;'-E#0H)"0EP87)S949A:6PH*3L-
M"@E]#0H)#0H)<')I=F%T92!B;V]L96%N(')E='5R;E-T;70H8F]O;&5A;B!R
M*0T*"7L-"@D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L
M<R@B<F5T=7)N(BDI#0H)"7L-"@D)"7(@/2!T<G5E.PT*"0D)86-C97!T*"D[
M#0H)"0ER971U<FY4=V\H*3L-"@D)?0T*"0EE;'-E#0H)"0EP87)S949A:6PH
M*3L-"@D)#0H)"7)E='5R;B!R.PT*"7T-"@D-"@EP<FEV871E('9O:60@<F5T
M=7)N5'=O*"D-"@E[#0H)"6EF*&YE>'14;VME;BYG9714>7!E*"DN8V]N=&5N
M=$5Q=6%L<R@B240B*2!\?`T*"0D)"6YE>'14;VME;BYG9714>7!E*"DN8V]N
M=&5N=$5Q=6%L<R@B3E5-(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5'EP92@I
M+F-O;G1E;G1%<75A;',H(D9,5"(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O
M:V5N*"DN8V]N=&5N=$5Q=6%L<R@B*"(I*0T*"0E[#0H)"0E%;&5M96YT(')T
M;B`](&5X<')E<W-I;VXH*3L-"@D)"6EF*&YE>'14;VME;BYG9714;VME;B@I
M+F-O;G1E;G1%<75A;',H(CLB*2D-"@D)"7L-"@D)"0EI9B@A<W0N;&]O:W5P
M*'-T+"!F=6YC+F=E=$YA;64H*2DN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H
M<G1N+F=E=%1Y<&4H*2D@?'P-"@D)"0D)"7)T;BYG971#;&%S<R@I(#T](&YE
M=R!!<G)A>45L96UE;G0H;F5W($5L96UE;G0H*2DN9V5T0VQA<W,H*2!\?`T*
M"0D)"0D)<G1N+F=E=$-L87-S*"D@/3T@;F5W($9U;D5L96UE;G0H;F5W($5L
M96UE;G0H*2DN9V5T0VQA<W,H*2D-"@D)"0E[#0H)"0D)"5-Y<W1E;2YO=70N
M<')I;G1L;B@B26YC;W)R96-T(')E='5R;B!T>7!E+B(I.PT*"0D)"0ES96U&
M86EL*"D[#0H)"0D)?0T*"0D)"6%C8V5P="@I.PT*"0D)?0T*"0D)#0H)"0EE
M;'-E#0H)"0D)<&%R<V5&86EL*"D[#0H)"7T-"@D)96QS92!I9BAN97AT5&]K
M96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"([(BDI#0H)"7L-"@D)"6EF
M*"%S="YL;V]K=7`H<W0L(&9U;F,N9V5T3F%M92@I*2YG9714>7!E*"DN8V]N
M=&5N=$5Q=6%L<R@B5D])1"(I*0T*"0D)>PT*"0D)"5-Y<W1E;2YO=70N<')I
M;G1L;B@B4F5T=7)N('1Y<&4@;6ES<VEN9RXB*3L-"@D)"0ES96U&86EL*"D[
M#0H)"0E]#0H)"0EA8V-E<'0H*3L-"@D)?0T*"0EE;'-E#0H)"0EP87)S949A
M:6PH*3L-"@E]#0H)#0H)<')I=F%T92!%;&5M96YT(&5X<')E<W-I;VXH*0T*
M"7L-"@D)16QE;65N="!E>'`@/2!N97<@16QE;65N="@I.PT*"0EI9BAN97AT
M5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(DE$(BDI#0H)"0EE>'`@
M/2!E>'!R97-S240H97AP*3L-"@D)96QS92!I9BAN97AT5&]K96XN9V5T5'EP
M92@I+F-O;G1E;G1%<75A;',H(DY532(I('Q\#0H)"0D);F5X=%1O:V5N+F=E
M=%1Y<&4H*2YC;VYT96YT17%U86QS*")&3%0B*2!\?`T*"0D)"6YE>'14;VME
M;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(B@B*2D-"@D)"65X<"`](&5X
M<')E<W-/=&AE<BAE>'`I.PT*"0EE;'-E#0H)"0EP87)S949A:6PH*3L-"@D)
M#0H)"7)E='5R;B!E>'`[#0H)?0T*"0T*"7!R:79A=&4@16QE;65N="!E>'!R
M97-S3W1H97(H16QE;65N="!E>'`I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T
M5'EP92@I+F-O;G1E;G1%<75A;',H(DY532(I('Q\#0H)"0D);F5X=%1O:V5N
M+F=E=%1Y<&4H*2YC;VYT96YT17%U86QS*")&3%0B*2!\?`T*"0D)"6YE>'14
M;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(B@B*2D-"@D)>PT*"0D)
M97AP(#T@9F%C=&]R06QT*&5X<"D[#0H)"0EE>'`@/2!T97)M5'=O*&5X<"D[
M#0H)"0EE>'`@/2!A9&1%>'!N5'=O*&5X<"D[#0H)"0EE>'`@/2!S:6UP;&5%
M>'!N*&5X<"D[#0H)"7T-"@D)#0H)"7)E='5R;B!E>'`[#0H)?0T*"0T*"7!R
M:79A=&4@16QE;65N="!E>'!R97-S240H16QE;65N="!E>'`I#0H)>PT*"0EI
M9BAN97AT5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(DE$(BDI#0H)
M"7L-"@D)"45L96UE;G0@96QE.PT*"0D):68H*&5L92`]("AS="YL;V]K=7`H
M<W0L(&YE>'14;VME;BYG9714;VME;B@I*2DI(#T](&YU;&PI#0H)"0D)<V5M
M1F%I;"@I.PT*"0D)96QS90T*"0D)"65X<"`](&5L92YC;&]N92@I.PT*"0D)
M#0H)"0EA8V-E<'0H*3L-"@D)?0T*"0EE;'-E#0H)"0EP87)S949A:6PH*3L-
M"@D)97AP(#T@97AP<F5S<TE$5'=O*&5X<"D[#0H)"0T*"0ER971U<FX@97AP
M.PT*"7T-"@D-"@EP<FEV871E($5L96UE;G0@97AP<F5S<TE$5'=O*$5L96UE
M;G0@97AP*0T*"7L-"@D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N
M=$5Q=6%L<R@B*"(I*0T*"0E[#0H)"0EI9BAE>'`N9V5T0VQA<W,H*2`A/2!N
M97<@1G5N16QE;65N="AN97<@16QE;65N="@I*2YG971#;&%S<R@I*0T*"0D)
M>PT*"0D)"5-Y<W1E;2YO=70N<')I;G1L;BAE>'`N9V5T3F%M92@I("L@(B!I
M<R!N;W0@82!F=6YC=&EO;BXB*3L-"@D)"0ES96U&86EL*"D[#0H)"0E]#0H)
M"0D)#0H)"0EE>'`@/2!C86QL*&YE=R!&=6Y%;&5M96YT*&5X<"YG971.86UE
M*"DL(&5X<"YG9714>7!E*"DI*3L-"@D)"65X<"`](&5X<')E<W-)1$-A;&PH
M97AP*3L-"@D)?0T*"0EE;'-E(&EF*&YE>'14;VME;BYG9714;VME;B@I+F-O
M;G1E;G1%<75A;',H(BLB*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I
M+F-O;G1E;G1%<75A;',H(BTB*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME
M;B@I+F-O;G1E;G1%<75A;',H(BHB*2!\?`T*"0D)"6YE>'14;VME;BYG9714
M;VME;B@I+F-O;G1E;G1%<75A;',H(B\B*2!\?`T*"0D)"6YE>'14;VME;BYG
M9714;VME;B@I+F-O;G1E;G1%<75A;',H(CTB*2!\?`T*"0D)"6YE>'14;VME
M;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(CP](BD@?'P-"@D)"0EN97AT
M5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(\(BD@?'P-"@D)"0EN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(^(BD@?'P-"@D)
M"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(^/2(I('Q\
M#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/3TB
M*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H
M(B$](BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U
M86QS*");(BDI#0H)"7L-"@D)"65X<"`]('9A<BAE>'`I.PT*"0D)97AP(#T@
M97AP<F5S<TE$5F%R*&5X<"D[#0H)"7T-"@D)96QS92!I9B@A*&YE>'14;VME
M;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(BDB*2!\?`T*"0D)"6YE>'14
M;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(ETB*2!\?`T*"0D)"6YE
M>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(BPB*2!\?`T*"0D)
M"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(CLB*2DI#0H)
M"0EP87)S949A:6PH*3L-"@D)#0H)"7)E='5R;B!E>'`[#0H)?0T*"0T*"7!R
M:79A=&4@16QE;65N="!E>'!R97-S241687(H16QE;65N="!E>'`I#0H)>PT*
M"0EI9BAN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(](BDI
M#0H)"7L-"@D)"6EF*&5X<"YG971#;&%S<R@I(#T](&YE=R!&=6Y%;&5M96YT
M*&YE=R!%;&5M96YT*"DI+F=E=$-L87-S*"DI#0H)"0E[#0H)"0D)4WES=&5M
M+F]U="YP<FEN=&QN*"),969T('-I9&4@:7,@82!F=6YC=&EO;BXB*3L-"@D)
M"0ES96U&86EL*"D[#0H)"0E]#0H)"0EA8V-E<'0H*3L-"@D)"45L96UE;G0@
M96QE(#T@97AP<F5S<VEO;B@I.PT*"0D):68H97AP+F=E=$-L87-S*"D@/3T@
M;F5W($%R<F%Y16QE;65N="AN97<@16QE;65N="@I*2YG971#;&%S<R@I*0D)
M#0H)"0E[#0H)"0D)4WES=&5M+F]U="YP<FEN=&QN*"),969T('-I9&4@:7,@
M87)R87D@=F%R:6%B;&4N(BD[#0H)"0D)<V5M1F%I;"@I.PT*"0D)?0T*"0D)
M96QS92!I9BAE;&4N9V5T0VQA<W,H*2`]/2!N97<@07)R87E%;&5M96YT*&YE
M=R!%;&5M96YT*"DI+F=E=$-L87-S*"D@)B8-"@D)"0D)97AP+F=E=$-L87-S
M*"D@(3T@96QE+F=E=$-L87-S*"DI#0H)"0E[#0H)"0D)4WES=&5M+F]U="YP
M<FEN=&QN*")!='1E;7!T('1O(&%S<VEG;B!U;FEN9&5X960@87)R87D@=F%R
M:6%B;&4N(BD[#0H)"0D)<V5M1F%I;"@I.PT*"0D)?0T*"0D)96QS92!I9B@A
M97AP+F=E=%1Y<&4H*2YC;VYT96YT17%U86QS*&5L92YG9714>7!E*"DI*0T*
M"0D)>PT*"0D)"5-Y<W1E;2YO=70N<')I;G1L;B@B5'EP92!E<G)O<CH@(B`K
M(&5X<"YG9714>7!E*"D@*R`B(#T@(B`K(&5L92YG9714>7!E*"DI.PT*"0D)
M"7-E;49A:6PH*3L-"@D)"7T-"@D)?0T*"0EE;'-E(&EF*&YE>'14;VME;BYG
M9714;VME;B@I+F-O;G1E;G1%<75A;',H(BLB*2!\?`T*"0D)"6YE>'14;VME
M;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(BTB*2!\?`T*"0D)"6YE>'14
M;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(BHB*2!\?`T*"0D)"6YE
M>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(B\B*2!\?`T*"0D)
M"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(CP](BD@?'P-
M"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(\(BD@
M?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(^
M(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS
M*"(^/2(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q
M=6%L<R@B/3TB*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E
M;G1%<75A;',H(B$](BDI#0H)"7L-"@D)"65X<"`]('1E<FU4=V\H97AP*3L-
M"@D)"65X<"`](&%D9$5X<&Y4=V\H97AP*3L-"@D)"65X<"`]('-I;7!L945X
M<&XH97AP*3L-"@D)?0T*"0EE;'-E(&EF*"$H;F5X=%1O:V5N+F=E=%1O:V5N
M*"DN8V]N=&5N=$5Q=6%L<R@B*2(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O
M:V5N*"DN8V]N=&5N=$5Q=6%L<R@B72(I('Q\#0H)"0D);F5X=%1O:V5N+F=E
M=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B.R(I('Q\#0H)"0D);F5X=%1O:V5N
M+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B+"(I*2D-"@D)"7!A<G-E1F%I
M;"@I.PT*"0D-"@D)<F5T=7)N(&5X<#L-"@E]#0H)#0H)<')I=F%T92!%;&5M
M96YT(&5X<')E<W-)1$-A;&PH16QE;65N="!E>'`I#0H)>PT*"0EI9BAN97AT
M5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(K(BD@?'P-"@D)"0EN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(M(BD@?'P-"@D)
M"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(J(BD@?'P-
M"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(O(BD@
M?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(\
M/2(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L
M<R@B/"(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q
M=6%L<R@B/B(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N
M=$5Q=6%L<R@B/CTB*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O
M;G1E;G1%<75A;',H(CT](BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH
M*2YC;VYT96YT17%U86QS*"(A/2(I*0T*"0E[#0H)"0EE>'`@/2!T97)M5'=O
M*&5X<"D[#0H)"0EE>'`@/2!A9&1%>'!N5'=O*&5X<"D[#0H)"0EE>'`@/2!S
M:6UP;&5%>'!N*&5X<"D[#0H)"7T-"@D)96QS92!I9BAN97AT5&]K96XN9V5T
M5&]K96XH*2YC;VYT96YT17%U86QS*"(I(BD@?'P-"@D)"0EN97AT5&]K96XN
M9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")=(BD@?'P-"@D)"0EN97AT5&]K
M96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(L(BD@?'P-"@D)"0EN97AT
M5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"([(BDI#0H)"0D[#0H)
M"65L<V4-"@D)"7!A<G-E1F%I;"@I.PT*"0D-"@D)<F5T=7)N(&5X<#L-"@E]
M#0H)#0H)<')I=F%T92!%;&5M96YT('9A<BA%;&5M96YT(&5X<"D-"@E[#0H)
M"6EF*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(ELB*2D-
M"@D)>PT*"0D):68H97AP+F=E=$-L87-S*"D@(3T@;F5W($%R<F%Y16QE;65N
M="AN97<@16QE;65N="@I*2YG971#;&%S<R@I*0T*"0D)>PT*"0D)"5-Y<W1E
M;2YO=70N<')I;G1L;B@B071T96UP="!T;R!I;F1E>"!N;VXM87)R87D@=F%R
M:6%B;&4N(BD[#0H)"0D)<V5M1F%I;"@I.PT*"0D)?0T*"0D)86-C97!T*"D[
M#0H)"0E%;&5M96YT(&D@/2!E>'!R97-S:6]N*"D[#0H)"0EI9B@A:2YG9714
M>7!E*"DN8V]N=&5N=$5Q=6%L<R@B3E5-(BDI#0H)"0E[#0H)"0D)4WES=&5M
M+F]U="YP<FEN=&QN*"));G9A;&ED(&%R<F%Y(&EN9&5X+B(I.PT*"0D)"7-E
M;49A:6PH*3L-"@D)"7T-"@D)"0T*"0D):68H;F5X=%1O:V5N+F=E=%1O:V5N
M*"DN8V]N=&5N=$5Q=6%L<R@B72(I*0T*"0D)>PT*"0D)"6%C8V5P="@I.PT*
M"0D)"45L96UE;G0@96QE(#T@;F5W($5L96UE;G0H97AP+F=E=%1Y<&4H*2D[
M#0H)"0D)97AP(#T@96QE.PT*"0D)?0T*"0D)96QS90T*"0D)"7!A<G-E1F%I
M;"@I.PT*"0E]#0H)"65L<V4@:68H(2AN97AT5&]K96XN9V5T5&]K96XH*2YC
M;VYT96YT17%U86QS*"(K(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH
M*2YC;VYT96YT17%U86QS*"(M(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K
M96XH*2YC;VYT96YT17%U86QS*"(J(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T
M5&]K96XH*2YC;VYT96YT17%U86QS*"(O(BD@?'P-"@D)"0EN97AT5&]K96XN
M9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(](BD@?'P-"@D)"0EN97AT5&]K
M96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(\/2(I('Q\#0H)"0D);F5X
M=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/"(I('Q\#0H)"0D)
M;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/B(I('Q\#0H)
M"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/CTB*2!\
M?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(CT]
M(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS
M*"(A/2(I*2D-"@D)"7!A<G-E1F%I;"@I.PT*"0D-"@D)<F5T=7)N(&5X<#L-
M"@E]#0H)#0H)<')I=F%T92!%;&5M96YT('-I;7!L945X<&XH16QE;65N="!E
M>'`I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U
M86QS*"(\/2(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N
M=$5Q=6%L<R@B/"(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N
M=&5N=$5Q=6%L<R@B/B(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN
M8V]N=&5N=$5Q=6%L<R@B/CTB*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME
M;B@I+F-O;G1E;G1%<75A;',H(CT](BD@?'P-"@D)"0EN97AT5&]K96XN9V5T
M5&]K96XH*2YC;VYT96YT17%U86QS*"(A/2(I*0T*"0E[#0H)"0ER96QO<"@I
M.PT*"0D)861D17AP;B@I.PT*"0E]#0H)"65L<V4@:68H(2AN97AT5&]K96XN
M9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(I(BD@?'P-"@D)"0EN97AT5&]K
M96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")=(BD@?'P-"@D)"0EN97AT
M5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(L(BD@?'P-"@D)"0EN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"([(BDI*0T*"0D)
M<&%R<V5&86EL*"D[#0H)"0T*"0ER971U<FX@97AP.PT*"7T-"@D-"@EP<FEV
M871E(%-T<FEN9R!R96QO<"@I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T5&]K
M96XH*2YC;VYT96YT17%U86QS*"(\/2(I('Q\#0H)"0D);F5X=%1O:V5N+F=E
M=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/"(I('Q\#0H)"0D);F5X=%1O:V5N
M+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/B(I('Q\#0H)"0D);F5X=%1O
M:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/CTB*2!\?`T*"0D)"6YE
M>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(CT](BD@?'P-"@D)
M"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(A/2(I*0T*
M"0E[#0H)"0E3=')I;F<@="`](&YE>'14;VME;BYG9714;VME;B@I.PT*"0D)
M86-C97!T*"D[#0H)"0ER971U<FX@=#L-"@D)?0T*"0ER971U<FX@;G5L;#L-
M"@E]#0H)#0H)<')I=F%T92!%;&5M96YT(&%D9$5X<&XH*0T*"7L-"@D)16QE
M;65N="!A(#T@;F5W($5L96UE;G0H*3L-"@D):68H;F5X=%1O:V5N+F=E=%1Y
M<&4H*2YC;VYT96YT17%U86QS*"))1"(I('Q\#0H)"0D);F5X=%1O:V5N+F=E
M=%1Y<&4H*2YC;VYT96YT17%U86QS*").54TB*2!\?`T*"0D)"6YE>'14;VME
M;BYG9714>7!E*"DN8V]N=&5N=$5Q=6%L<R@B1DQ4(BD@?'P-"@D)"0EN97AT
M5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(H(BDI#0H)"7L-"@D)
M"6$@/2!T97)M*"D[#0H)"0EA(#T@861D17AP;E1W;RAA*3L-"@D)?0T*"0EE
M;'-E#0H)"0EP87)S949A:6PH*3L-"@D)#0H)"7)E='5R;B!A.PT*"7T-"@D-
M"@EP<FEV871E($5L96UE;G0@861D17AP;E1W;RA%;&5M96YT(&5X<"D-"@E[
M#0H)"6EF*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(BLB
M*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H
M(BTB*2D-"@D)>PT*"0D)4W1R:6YG(&]P(#T@861D;W`H*3L-"@D)"45L96UE
M;G0@="`]('1E<FTH*3L-"@D)"6EF*&]P+F-O;G1E;G1%<75A;',H(BLB*2!\
M?"!O<"YC;VYT96YT17%U86QS*"(M(BDI#0H)"0E[#0H)"0D):68H97AP+F=E
M=$-L87-S*"D@/3T@;F5W($%R<F%Y16QE;65N="AN97<@16QE;65N="@I*2YG
M971#;&%S<R@I("8F#0H)"0D)"70N9V5T0VQA<W,H*2`A/2!E>'`N9V5T0VQA
M<W,H*2D-"@D)"0E[#0H)"0D)"5-Y<W1E;2YO=70N<')I;G1L;B@B071T96UP
M="!T;R!O<&5R871E(&]N(&YO;BUI;F1E>&5D(&%R<F%Y('9A<FEA8FQE+B(I
M.PT*"0D)"0ES96U&86EL*"D[#0H)"0D)?0T*"0D)"65L<V4@:68H(65X<"YG
M9714>7!E*"DN8V]N=&5N=$5Q=6%L<RAT+F=E=%1Y<&4H*2DI#0H)"0D)>PT*
M"0D)"0E3>7-T96TN;W5T+G!R:6YT;&XH(E1Y<&4@97)R;W(Z("(K97AP+F=E
M=%1Y<&4H*2LB("(K;W`K(B`B*W0N9V5T5'EP92@I*3L-"@D)"0D)<V5M1F%I
M;"@I.PT*"0D)"7T-"@D)"7T-"@D)"65X<"`](&%D9$5X<&Y4=V\H97AP*3L-
M"@D)?0T*"0EE;'-E(&EF*&YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%
M<75A;',H(CP](BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT
M96YT17%U86QS*"(\(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC
M;VYT96YT17%U86QS*"(^(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH
M*2YC;VYT96YT17%U86QS*"(^/2(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O
M:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/3TB*2!\?`T*"0D)"6YE>'14;VME;BYG
M9714;VME;B@I+F-O;G1E;G1%<75A;',H(B$](BD@?'P-"@D)"0EN97AT5&]K
M96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(I(BD@?'P-"@D)"0EN97AT
M5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*")=(BD@?'P-"@D)"0EN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(L(BD@?'P-"@D)
M"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"([(BDI#0H)
M"3L-"@D)96QS90T*"0D)<&%R<V5&86EL*"D[#0H)"0T*"0ER971U<FX@97AP
M.PT*"7T-"@D-"@EP<FEV871E(%-T<FEN9R!A9&1O<"@I#0H)>PT*"0EI9BAN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(K(BD@?'P@;F5X
M=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B+2(I*0T*"0E[#0H)
M"0E3=')I;F<@;R`](&YE>'14;VME;BYG9714;VME;B@I.PT*"0D)86-C97!T
M*"D[#0H)"0ER971U<FX@;SL-"@D)?0T*"0EE;'-E#0H)"0EP87)S949A:6PH
M*3L-"@D)#0H)"7)E='5R;B!N=6QL.PT*"7T-"@D-"@EP<FEV871E($5L96UE
M;G0@=&5R;2@I#0H)>PT*"0E%;&5M96YT('0@/2!N97<@16QE;65N="@I.PT*
M"0EI9BAN97AT5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(DE$(BD@
M?'P-"@D)"0EN97AT5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(DY5
M32(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1Y<&4H*2YC;VYT96YT17%U86QS
M*")&3%0B*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%
M<75A;',H(B@B*2D-"@D)>PT*"0D)="`](&9A8W1O<BAT*3L-"@D)"70@/2!T
M97)M5'=O*'0I.PT*"0E]#0H)"65L<V4-"@D)"7!A<G-E1F%I;"@I.PT*"0D-
M"@D)<F5T=7)N('0[#0H)?0T*"0T*"7!R:79A=&4@16QE;65N="!T97)M5'=O
M*$5L96UE;G0@97AP*0T*"7L-"@D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN
M8V]N=&5N=$5Q=6%L<R@B*B(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N
M*"DN8V]N=&5N=$5Q=6%L<R@B+R(I*0T*"0E[#0H)"0E3=')I;F<@;W`@/2!M
M=6QO<"@I.PT*"0D)16QE;65N="!T(#T@9F%C=&]R*&YE=R!%;&5M96YT*"DI
M.PT*"0D):68H;W`N8V]N=&5N=$5Q=6%L<R@B*B(I('Q\(&]P+F-O;G1E;G1%
M<75A;',H(B\B*2D-"@D)"7L-"@D)"0EI9BAE>'`N9V5T0VQA<W,H*2`]/2!N
M97<@07)R87E%;&5M96YT*&YE=R!%;&5M96YT*"DI+F=E=$-L87-S*"D@)B8-
M"@D)"0D)"70N9V5T0VQA<W,H*2`A/2!E>'`N9V5T0VQA<W,H*2D-"@D)"0E[
M#0H)"0D)"0E3>7-T96TN;W5T+G!R:6YT;&XH(D%T=&5M<'0@=&\@;W!E<F%T
M92!O;B!N;VXM:6YD97AE9"!A<G)A>2!V87)I86)L92XB*3L-"@D)"0D)"7-E
M;49A:6PH*3L-"@D)"0E]#0H)"0D)96QS92!I9B@A97AP+F=E=%1Y<&4H*2YC
M;VYT96YT17%U86QS*'0N9V5T5'EP92@I*2D-"@D)"0E[#0H)"0D)"5-Y<W1E
M;2YO=70N<')I;G1L;B@B5'EP92!E<G)O<CH@(BME>'`N9V5T5'EP92@I*R(@
M(BMO<"LB("(K="YG9714>7!E*"DI.PT*"0D)"0ES96U&86EL*"D[#0H)"0D)
M?0T*"0D)?0T*"0D)"0T*"0D)97AP(#T@=&5R;51W;RAE>'`I.PT*"0E]#0H)
M"65L<V4@:68H(2AN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS
M*"(K(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U
M86QS*"(M(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT
M17%U86QS*"(\/2(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N
M=&5N=$5Q=6%L<R@B/"(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN
M8V]N=&5N=$5Q=6%L<R@B/B(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N
M*"DN8V]N=&5N=$5Q=6%L<R@B/CTB*2!\?`T*"0D)"6YE>'14;VME;BYG9714
M;VME;B@I+F-O;G1E;G1%<75A;',H(CT](BD@?'P-"@D)"0EN97AT5&]K96XN
M9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(A/2(I('Q\#0H)"0D);F5X=%1O
M:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B*2(I('Q\#0H)"0D);F5X
M=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B72(I('Q\#0H)"0D)
M;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B+"(I('P-"@D)
M"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"([(BDI*0T*
M"0D)<&%R<V5&86EL*"D[#0H)"0T*"0ER971U<FX@97AP.PT*"7T-"@D-"@EP
M<FEV871E(%-T<FEN9R!M=6QO<"@I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T
M5&]K96XH*2YC;VYT96YT17%U86QS*"(J(BDI#0H)"7L-"@D)"6%C8V5P="@I
M.PT*"0D)<F5T=7)N("(J(CL)"0T*"0E]#0H)"65L<V4@:68H;F5X=%1O:V5N
M+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B+R(I*0T*"0E[#0H)"0EA8V-E
M<'0H*3L-"@D)"7)E='5R;B`B+R([#0H)"7T-"@D)96QS90T*"0D)<&%R<V5&
M86EL*"D[#0H)"0T*"0ER971U<FX@;G5L;#L-"@E]#0H)#0H)<')I=F%T92!%
M;&5M96YT(&9A8W1O<BA%;&5M96YT(&5X<"D-"@E[#0H)"6EF*&YE>'14;VME
M;BYG9714>7!E*"DN8V]N=&5N=$5Q=6%L<R@B240B*2D-"@D)>PT*"0D)97AP
M(#T@<W0N;&]O:W5P*'-T+"!N97AT5&]K96XN9V5T5&]K96XH*2DN8VQO;F4H
M*3L-"@D)"6%C8V5P="@I.PT*"0D)97AP(#T@:61E;BAE>'`I.PT*"0E]#0H)
M"65L<V4@:68H;F5X=%1O:V5N+F=E=%1Y<&4H*2YC;VYT96YT17%U86QS*").
M54TB*2!\?`T*"0D)"6YE>'14;VME;BYG9714>7!E*"DN8V]N=&5N=$5Q=6%L
M<R@B1DQ4(BDI#0H)"7L-"@D)"65X<"YS9714>7!E*&YE>'14;VME;BYG9714
M>7!E*"DI.PT*"0D)97AP+G-E=%9A;'5E*&YE>'14;VME;BYG9714;VME;B@I
M*3L-"@D)"6%C8V5P="@I.PT*"0E]#0H)"65L<V4@:68H;F5X=%1O:V5N+F=E
M=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B*"(I*0T*"0E[#0H)"0EA8V-E<'0H
M*3L-"@D)"65X<"`](&5X<')E<W-I;VXH*3L-"@D)"6EF*&YE>'14;VME;BYG
M9714;VME;B@I+F-O;G1E;G1%<75A;',H(BDB*2D-"@D)"0EA8V-E<'0H*3L-
M"@D)"65L<V4-"@D)"0EP87)S949A:6PH*3L-"@D)?0T*"0D-"@D)<F5T=7)N
M(&5X<#L-"@E]#0H)#0H)<')I=F%T92!%;&5M96YT(&9A8W1O<D%L="A%;&5M
M96YT(&5X<"D-"@E[#0H)"6EF*&YE>'14;VME;BYG9714>7!E*"DN8V]N=&5N
M=$5Q=6%L<R@B3E5-(BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5'EP92@I+F-O
M;G1E;G1%<75A;',H(D9,5"(I*0T*"0E[#0H)"0EE>'`N<V5T5'EP92AN97AT
M5&]K96XN9V5T5'EP92@I*3L-"@D)"65X<"YS971686QU92AN97AT5&]K96XN
M9V5T5&]K96XH*2D[#0H)"0EA8V-E<'0H*3L-"@D)?0T*"0EE;'-E(&EF*&YE
M>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A;',H(B@B*2D-"@D)>PT*
M"0D)86-C97!T*"D[#0H)"0EE>'`@/2!E>'!R97-S:6]N*"D[#0H)"0EI9BAN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(I(BDI#0H)"0D)
M86-C97!T*"D[#0H)"0EE;'-E#0H)"0D)<&%R<V5&86EL*"D[#0H)"7T-"@D)
M#0H)"7)E='5R;B!E>'`[#0H)?0T*"0T*"7!R:79A=&4@16QE;65N="!I9&5N
M*$5L96UE;G0@97AP*0T*"7L-"@D):68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN
M8V]N=&5N=$5Q=6%L<R@B*"(I*0T*"0D)97AP(#T@8V%L;"AN97<@1G5N16QE
M;65N="AE>'`N9V5T3F%M92@I+"!E>'`N9V5T5'EP92@I*2D[#0H)"65L<V4@
M:68H;F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B6R(I*0T*
M"0D)97AP(#T@=F%R*&5X<"D[#0H)"65L<V4@:68H(2AN97AT5&]K96XN9V5T
M5&]K96XH*2YC;VYT96YT17%U86QS*"(K(BD@?'P-"@D)"0EN97AT5&]K96XN
M9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(M(BD@?'P-"@D)"0EN97AT5&]K
M96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(J(BD@?'P-"@D)"0EN97AT
M5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(O(BD@?'P-"@D)"0EN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(\/2(I('Q\#0H)
M"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/"(I('Q\
M#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B/B(I
M('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B
M/CTB*2!\?`T*"0D)"6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E;G1%<75A
M;',H(CT](BD@?'P-"@D)"0EN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT
M17%U86QS*"(A/2(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N
M=&5N=$5Q=6%L<R@B*2(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN
M8V]N=&5N=$5Q=6%L<R@B72(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O:V5N
M*"DN8V]N=&5N=$5Q=6%L<R@B+"(I('Q\#0H)"0D);F5X=%1O:V5N+F=E=%1O
M:V5N*"DN8V]N=&5N=$5Q=6%L<R@B.R(I*2D-"@D)"7!A<G-E1F%I;"@I.PT*
M"0D-"@D)<F5T=7)N(&5X<#L-"@E]#0H)#0H)<')I=F%T92!%;&5M96YT(&-A
M;&PH1G5N16QE;65N="!E>'`I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T5&]K
M96XH*2YC;VYT96YT17%U86QS*"(H(BDI#0H)"7L-"@D)"6%C8V5P="@I.PT*
M"0D)97AP(#T@87)G<RAE>'`I.PT*"0D):68H;F5X=%1O:V5N+F=E=%1O:V5N
M*"DN8V]N=&5N=$5Q=6%L<R@B*2(I*0T*"0D)"6%C8V5P="@I.PT*"0D)96QS
M90T*"0D)"7!A<G-E1F%I;"@I.PT*"0D)#0H)"0EI9BAE>'`N9V5T4&%R86US
M*"DN<VEZ92@I(#T](#`I#0H)"0D)97AP+F%D9%!A<F%M*&YE=R!%;&5M96YT
M*")63TE$(BDI.PT*"0D)#0H)"0E&=6Y%;&5M96YT(&8@/2`H1G5N16QE;65N
M="ES="YL;V]K=7`H<W0L(&5X<"YG971.86UE*"DI.PT*"0D):68H97AP+F=E
M=%!A<F%M<R@I+G-I>F4H*2`A/2!F+F=E=%!A<F%M<R@I+G-I>F4H*2D-"@D)
M"7L-"@D)"0E3>7-T96TN;W5T+G!R:6YT;&XH(DUI<VUA=&-H960@<&%R86UE
M=&5R<R`F(&%R9W5M96YT<RXB*3L-"@D)"0ES96U&86EL*"D[#0H)"0E]#0H)
M"0D-"@D)"0T*"0D)9F]R*&EN="!I(#T@,#L@:2`\(&5X<"YG971087)A;7,H
M*2YS:7IE*"D[(&DK*RD-"@D)"7L)#0H)"0D):68H*&8N9V5T4&%R86US*"DN
M9V5T*&DI+F=E=$-L87-S*"D@/3T@;F5W($%R<F%Y16QE;65N="AN97<@16QE
M;65N="@I*2YG971#;&%S<R@I("8F(`T*"0D)"0D)97AP+F=E=%!A<F%M<R@I
M+F=E="AI*2YG971#;&%S<R@I("$](&8N9V5T4&%R86US*"DN9V5T*&DI+F=E
M=$-L87-S*"DI('Q\#0H)"0D)"0DA97AP+F=E=%!A<F%M<R@I+F=E="AI*2YG
M9714>7!E*"DN8V]N=&5N=$5Q=6%L<RAF+F=E=%!A<F%M<R@I+F=E="AI*2YG
M9714>7!E*"DI*0T*"0D)"7L-"@D)"0D)4WES=&5M+F]U="YP<FEN=&QN*")-
M:7-M871C:&5D('!A<F%M971E<G,@)B!A<F=U;65N=',N(BD[#0H)"0D)"7-E
M;49A:6PH*3L-"@D)"0E]#0H)"0E]#0H)"7T-"@D)96QS90T*"0D)<&%R<V5&
M86EL*"D[#0H)"0T*"0E%;&5M96YT(&5L92`](&YE=R!687)%;&5M96YT*&5X
M<"D[#0H)"7)E='5R;B!E;&4[#0H)?0T*"0T*"7!R:79A=&4@1G5N16QE;65N
M="!A<F=S*$9U;D5L96UE;G0@97AP*0T*"7L-"@D):68H;F5X=%1O:V5N+F=E
M=%1Y<&4H*2YC;VYT96YT17%U86QS*"))1"(I('Q\#0H)"0D);F5X=%1O:V5N
M+F=E=%1Y<&4H*2YC;VYT96YT17%U86QS*").54TB*2!\?`T*"0D)"6YE>'14
M;VME;BYG9714>7!E*"DN8V]N=&5N=$5Q=6%L<R@B1DQ4(BD@?'P-"@D)"0EN
M97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT17%U86QS*"(H(BDI#0H)"0EE
M>'`@/2!A<F=,:7-T*&5X<"D[#0H)"65L<V4@:68H(2AN97AT5&]K96XN9V5T
M5&]K96XH*2YC;VYT96YT17%U86QS*"(I(BDI*0T*"0D)<&%R<V5&86EL*"D[
M#0H)"0T*"0ER971U<FX@97AP.PT*"7T-"@D-"@EP<FEV871E($9U;D5L96UE
M;G0@87)G3&ES="A&=6Y%;&5M96YT(&5X<"D-"@E[#0H)"6EF*&YE>'14;VME
M;BYG9714>7!E*"DN8V]N=&5N=$5Q=6%L<R@B240B*2!\?`T*"0D)"6YE>'14
M;VME;BYG9714>7!E*"DN8V]N=&5N=$5Q=6%L<R@B3E5-(BD@?'P-"@D)"0EN
M97AT5&]K96XN9V5T5'EP92@I+F-O;G1E;G1%<75A;',H(D9,5"(I('Q\#0H)
M"0D);F5X=%1O:V5N+F=E=%1O:V5N*"DN8V]N=&5N=$5Q=6%L<R@B*"(I*0T*
M"0E[#0H)"0EE>'`N861D4&%R86TH97AP<F5S<VEO;B@I*3L-"@D)"65X<"`]
M(&%R9TQI<W14=V\H97AP*3L-"@D)?0T*"0D-"@D)<F5T=7)N(&5X<#L-"@E]
M#0H)#0H)<')I=F%T92!&=6Y%;&5M96YT(&%R9TQI<W14=V\H1G5N16QE;65N
M="!E>'`I#0H)>PT*"0EI9BAN97AT5&]K96XN9V5T5&]K96XH*2YC;VYT96YT
M17%U86QS*"(L(BDI#0H)"7L-"@D)"6%C8V5P="@I.PT*"0D)97AP+F%D9%!A
M<F%M*&5X<')E<W-I;VXH*2D[#0H)"0EE>'`@/2!A<F=,:7-T5'=O*&5X<"D[
M"0T*"0E]#0H)"65L<V4@:68H(6YE>'14;VME;BYG9714;VME;B@I+F-O;G1E
M;G1%<75A;',H(BDB*2D-"@D)"7!A<G-E1F%I;"@I.PT*"0D-"@D)<F5T=7)N
M(&5X<#L-"@E]#0H)#0H)+RH)365T:&]D(&9O<B!E;F1I;F<@<WEN=&%C=&EC
M(&%N86QY<VES(&EN(&5R<F]R(&EF(&%N#0H)("H@"75N9&5F:6YE9"!S=&%T
M92!I<R!E;F-O=6YT97)E9"X@#0H)("HO#0H)<')I=F%T92!V;VED('!A<G-E
M1F%I;"@I#0H)>PT*"0E3>7-T96TN;W5T+G!R:6YT;&XH(E!A<G-E(&9A:6QE
M9"XB*3L-"@D)4WES=&5M+F5X:70H,2D[#0H)?0T*"0T*"2\J"4UE=&AO9"!F
M;W(@96YD:6YG('-E;6%N=&EC(&%N86QY<VES(&EN(&5R<F]R(&EF(&%N#0H)
M("H@('5N9&5F:6YE9"!S=&%T92!I<R!E;F-O=6YT97)E9"X-"@D@*B\-"@EP
M<FEV871E('9O:60@<V5M1F%I;"@I#0H)>PT*"0E3>7-T96TN;W5T+G!R:6YT
M;&XH(E-E;6%N=&EC(&%N86QY<VES(&9A:6QE9"XB*3L-"@D)4WES=&5M+F5X
-:70H,2D[#0H)?0T*?6%N
`
end
SHAR_EOF
  (set 20 13 04 04 23 48 15 'Parser.java'; eval "$shar_touch") &&
  chmod 0644 'Parser.java'
if test $? -ne 0
then ${echo} 'restore of Parser.java failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'Parser.java: MD5 check failed'
       ) << \SHAR_EOF
638f61e6b2f47d4bef68e0c99283f460  Parser.java
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'Parser.java'` -ne 27148 && \
  ${echo} 'restoration warning:  size of Parser.java is not 27148'
  fi
fi
# ============= Semantic.java ==============
if test -f 'Semantic.java' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING Semantic.java (file already exists)'
else
${echo} 'x - extracting Semantic.java (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 Semantic.java
M+RH)0T]0-#8R,"`M(%!R;VIE8W0@,PT*("H)4W1E<&AE;B!297!P97(-"B`J
M+PT*#0II;7!O<G0@:F%V82YI;RY&:6QE.PT*#0IP=6)L:6,@8VQA<W,@4V5M
M86YT:6,@>PT*"49I;&4@9FEL93L-"@E,97AI8V%L06YA;'EZ97(@;&5X.PT*
M"5!A<G-E<B!P87)S97([#0H)5&]K96X@;F5X=%1O:V5N.PT*"5-Y;6)O;%1A
M8FQE('-T.PT*#0H)<'5B;&EC('-T871I8R!V;VED(&UA:6XH4W1R:6YG6UT@
M87)G<RD-"@E[#0H)"71R>0T*"0E[#0H)"0EN97<@4V5M86YT:6,H87)G<ULP
M72D[#0H)"0D-"@D)?0T*"0EC871C:"A!<G)A>4EN9&5X3W5T3V9";W5N9'-%
M>&-E<'1I;VX@92D-"@D)>PT*"0D)4WES=&5M+F]U="YP<FEN=&QN*").;R!D
M871A(&9I;&4@<')E<V5N="XB*3L-"@D)?0T*"0EC871C:"A%>&-E<'1I;VX@
M92D-"@D)>PT*"0D)4WES=&5M+F]U="YP<FEN=&QN*"(^("(@*R!E+F=E=$UE
M<W-A9V4H*2D[#0H)"7T-"@E]#0H)#0H)+RH)0V]N<W1R=6-T;W(@;W!E;G,@
M9FEL92P@<V5N9',@:70@=&\@3&5X:6-A;$%N86QY>F5R+"!C;&]S97,@=&AE
M#0H)("H@"6QO8V%L(&9I;&4L(&%N9"!C<F5A=&5S("8@<G5N<R!T:&4@4&%R
M<V5R+@T*"2`J+PT*"7!U8FQI8R!396UA;G1I8RA3=')I;F<@87)G*2!T:')O
M=W,@17AC97!T:6]N#0H)>PT*"0ES="`](&YE=R!3>6UB;VQ486)L92@I.PT*
M"0EF:6QE(#T@;F5W($9I;&4H87)G*3L-"@D)<&%R<V5R(#T@;F5W(%!A<G-E
M<BAF:6QE+"!S="D[#0H)"69I;&4@/2!N=6QL.PT*"0ES="`]('!A<G-E<BYR
1=6XH*3L-"@E]#0H)#0I]#0II
`
end
SHAR_EOF
  (set 20 13 04 04 21 14 06 'Semantic.java'; eval "$shar_touch") &&
  chmod 0644 'Semantic.java'
if test $? -ne 0
then ${echo} 'restore of Semantic.java failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'Semantic.java: MD5 check failed'
       ) << \SHAR_EOF
59f1d93d8400ffe2357bb6c6239432e0  Semantic.java
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'Semantic.java'` -ne 782 && \
  ${echo} 'restoration warning:  size of Semantic.java is not 782'
  fi
fi
# ============= SymbolTable.java ==============
if test -f 'SymbolTable.java' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING SymbolTable.java (file already exists)'
else
${echo} 'x - extracting SymbolTable.java (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 SymbolTable.java
M+RH)0T]0-#8R,"`M(%!R;VIE8W0@,PT*("H)4W1E<&AE;B!297!P97(-"B`J
M+PT*#0IP=6)L:6,@8VQA<W,@4WEM8F]L5&%B;&4@>PT*"69I;F%L('!R:79A
M=&4@:6YT(%1325I%(#T@-3,[(`T*"7!R:79A=&4@16QE;65N=%M=(&5L96UE
M;G1S.PT*"7!R:79A=&4@4WEM8F]L5&%B;&4@;F5X=#L-"@EP<FEV871E(%-Y
M;6)O;%1A8FQE('!R978[#0H)#0H)<'5B;&EC(%-Y;6)O;%1A8FQE*"D-"@E[
M#0H)"65L96UE;G1S(#T@;F5W($5L96UE;G1;5%-)6D5=.PT*"7T-"@D-"@EP
M=6)L:6,@8F]O;&5A;B!I;G-E<G0H16QE;65N="!E*0T*"7L-"@D):6YT(&AA
M<VA686P@/2!H87-H*&4N9V5T3F%M92@I*3L-"@D):6YT('-T87)T(#T@:&%S
M:%9A;#L-"@D)=VAI;&4H96QE;65N='-;:&%S:%9A;%T@(3T@;G5L;"D-"@D)
M>PT*"0D):68H96QE;65N='-;:&%S:%9A;%TN9V5T3F%M92@I+F-O;G1E;G1%
M<75A;',H92YG971.86UE*"DI*0T*"0D)>PT*"0D)"5-Y<W1E;2YO=70N<')I
M;G1L;B@B16QE;65N="`B("L@92YG971.86UE*"D@*R`-"@D)"0D)"0D)"2(@
M86QR96%D>2!E>&ES=',@:6X@<WEM8F]L('1A8FQE+B(I.PT*"0D)"7)E='5R
M;B!F86QS93L-"@D)"7T-"@D)"6AA<VA686P@/2`H:&%S:%9A;"`K(#$I("4@
M5%-)6D4[#0H)"0EI9BAH87-H5F%L(#T]('-T87)T*0T*"0D)>PT*"0D)"5-Y
M<W1E;2YO=70N<')I;G1L;B@B3&]C86P@<WEM8F]L('1A8FQE(&9U;&PN(BD[
M#0H)"0D)<F5T=7)N(&9A;'-E.PT*"0D)?0T*"0E]#0H)"65L96UE;G1S6VAA
M<VA686Q=(#T@93L-"@D)<F5T=7)N('1R=64[#0H)?0T*"0T*"7!U8FQI8R!%
M;&5M96YT(&QO;VMU<"A3>6UB;VQ486)L92!T86)L92P@4W1R:6YG(&YA;64I
M#0H)>PT*"0E%;&5M96YT(')E="`](&YU;&P[#0H)"7)E="`](&=E="AT86)L
M92P@;F%M92D[#0H)"6EF*')E="`]/2!N=6QL*0T*"0D)4WES=&5M+F]U="YP
M<FEN=&QN*")!='1E;7!T('1O('5S92!U;F1E8VQA<F5D('-Y;6)O;"XB*3L-
M"@D)#0H)"7)E='5R;B!R970[#0H)?0T*"0T*"7!U8FQI8R!%;&5M96YT(&=E
M="A3>6UB;VQ486)L92!T86)L92P@4W1R:6YG(&YA;64I#0H)>PT*"0EI;G0@
M:&%S:%9A;"`](&AA<V@H;F%M92D[#0H)"6EN="!S=&%R="`](&AA<VA686P[
M#0H)"0T*"0EW:&EL92AT86)L92YE;&5M96YT<UMH87-H5F%L72`A/2!N=6QL
M("8F("%T86)L92YE;&5M96YT<UMH87-H5F%L72YG971.86UE*"DN8V]N=&5N
M=$5Q=6%L<RAN86UE*2D-"@D)>PT*"0D):&%S:%9A;"`]("AH87-H5F%L("L@
M,2D@)2!44TE:13L-"@D)"6EF*&AA<VA686P@/3T@<W1A<G0I#0H)"0D)8G)E
M86L[#0H)"7T-"@D)#0H)"6EF*'1A8FQE+F5L96UE;G1S6VAA<VA686Q=("$]
M(&YU;&P@)B8@=&%B;&4N96QE;65N='-;:&%S:%9A;%TN9V5T3F%M92@I+F-O
M;G1E;G1%<75A;',H;F%M92DI#0H)"0ER971U<FX@=&%B;&4N96QE;65N='-;
M:&%S:%9A;%T[#0H)"65L<V4@:68H=&%B;&4N<')E=B`A/2!N=6QL*0T*"0D)
M<F5T=7)N(&=E="AT86)L92YP<F5V+"!N86UE*3L-"@D)96QS90T*"0D)<F5T
M=7)N(&YU;&P[#0H)?0T*"0T*"7!U8FQI8R!I;G0@:&%S:"A3=')I;F<@<RD-
M"@E[#0H)"6EN="!R971686P@/2`P.PT*"0EF;W(H:6YT(&D@/2`P.R!I(#P@
M<RYL96YG=&@H*3L@:2LK*0T*"0E[#0H)"0ER971686P@/2`H<F5T5F%L("L@
M*"AI;G0I36%T:"YP;W<H."P@:2LQ*2`J(',N8VAA<D%T*&DI*2D@)2!44TE:
M13L-"@D)?0T*"0D-"@D)<F5T=7)N(')E=%9A;#L-"@E]#0H)#0H)<'5B;&EC
M('9O:60@861D5&%B;&4H*0T*"7L-"@D);F5X="`](&YE=R!3>6UB;VQ486)L
M92@I.PT*"0EN97AT+G-E=%!R979I;W5S*'1H:7,I.PT*"7T-"@D-"@EP=6)L
M:6,@4WEM8F]L5&%B;&4@9V5T3F5X="@I#0H)>PT*"0ER971U<FX@;F5X=#L-
M"@E]#0H)#0H)<'5B;&EC(%-Y;6)O;%1A8FQE(&=E=%!R978H*0T*"7L-"@D)
M<F5T=7)N('!R978[#0H)?0T*"0T*"7!U8FQI8R!V;VED('-E=%!R979I;W5S
K*%-Y;6)O;%1A8FQE('-T*0T*"7L-"@D)<')E=B`]('-T.PT*"7T-"GT-"G5S
`
end
SHAR_EOF
  (set 20 13 04 04 21 11 48 'SymbolTable.java'; eval "$shar_touch") &&
  chmod 0644 'SymbolTable.java'
if test $? -ne 0
then ${echo} 'restore of SymbolTable.java failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'SymbolTable.java: MD5 check failed'
       ) << \SHAR_EOF
7d1c9741f3c05af1caf35b2b14649698  SymbolTable.java
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'SymbolTable.java'` -ne 2023 && \
  ${echo} 'restoration warning:  size of SymbolTable.java is not 2023'
  fi
fi
# ============= TestFiles.zip ==============
if test -f 'TestFiles.zip' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING TestFiles.zip (file already exists)'
else
${echo} 'x - extracting TestFiles.zip (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 TestFiles.zip
M4$L#!!0````(`$N]@T*=1CY#.0```$$````E````87)R87DM:6YD97@M8V]M
M<&QE>"UE>'!R97-S:6]N+6]K+G1X="O+STQ1R$W,S-,H`[(T>;FJ>;D4,O-*
M%"JLH8S*:$.#6!"G,KI"2\-(VT@S5L%6P0PH4LO+Q<L%`%!+`P04````"``O
MKX-"XMZ=?S`````R````$@```&%R<F%Y+6EN9&5X+6]K+G1X="O+STQ1R$W,
MS-,H`[(T>;FJ>;D4,O-*%"JC#0UBK8&<RFC36`5;!3,@NY:7BY<+`%!+`P04
M````"`"6N(-"7/!=P#@```!$````%@```&%R<F%Y+6EN9&5X+79A<BUO:RYT
M>'0KR\],4<A-S,S3*`.R-'FYJGFY%#+S2A0JK*&,RFA#@U@0IT+!5L$4Q*B,
MKH@%LLV`[%I>+EXN`%!+`P04````"``N`(1"KAQ<N$X```!@````'P```&%S
M<VEG;FUE;G0M9&%T871Y<&5S+3(M9F%I;"YT>'0KR\],4<A-S,S3*`.R-'FY
MJGFY%#+S2A0JK(&,M)S\Q!*%$FNH6&6TH4$LB`-DQ"K8*IA8*P`Y%;;F(+$2
MH("YGH&"%E@6*%++R\7+!0!02P,$%`````@`=+^#0G`^CS4Z````10```!T`
M``!A<W-I9VYM96YT+61A=&%T>7!E<RUF86EL+G1X="O+STQ1R$W,S-,H`[(T
M>;FJ>;D4,O-*%"JLH8S*:$.#6!`'R(A5L%4PT3.U5@!R*VS-@:*UO%R\7`!0
M2P,$%`````@`[$Z$0G1X.Z$R`P``>0@```<```!B<V]R="YCG55+;Q,Q$#[7
MOV)N)"5)GT"J!:0B@=0;$I4X5#TX66_68==>V4[34N6_,S/V/@*T%?BR]G@>
MWWPSGCTZA,-_70*Z]6FS6%0*OED7M%G!9;6R3H>RAL_WLFXJ-5"=OK#$5V=7
M3M80Y`_E04(I7;ZTN<I!.B<?P!:P5"Y(;<!LZH5R7DB3@\?8'D*I:MAX`B'!
M:XH-BPB.%$"VR(1X*;T_%QP>":%-@%K>9T(<_0=G>VO`RG!=EVI(*'S9F&70
MUCRA_B21Y*=(MK"TQFN/#"%]1OF`=%;6-D@P<:<+YL[9S:HD#A/5?BN;AK@4
MC=0NVD;*P=XIQ[9QLZ)R;$S0%>@`VD.AC:RJ!V9=Y3/QO52&KFJNJ@ZO2,7Y
M`(WT?D(W2ULWTBFN8;H+6]O5>&0=J$K5R@0_)B0=S!E<%0.C:$`85D[)@-M0
M2B-(P2ND(4\:DX24DT0ZMM@6I-IZF%$A&+/8@Y:<4.ZAU"[O*'D.H4@0]Q#\
MCI$UV.??L(D];%=$&/)M-@@KM]MH7&FC^C*4$OU;H]K*,@>(3KL.U_5>6:2Q
MJ.*X)ET[X&UNL0DB@[)FB&;%$))9-"@H?[DL6Q)FV+Z@"_0:HPG",^\HF@P:
M;:NK"A:*&U'E7>@Y!%TKC_3M]7*<#*=HN]JPJ^FT=Z6#5U4QHF<J;V['7">&
MGCC'NK0(0)L>`UN8,<9ZZ=D^OVA(W%F=I[%#+W@$"<V$-P;&`.(1GRZ^:!+H
MC#_K^`EUD]$%?(!CVFQ+C9-@I.$]PHM&`(_M!F"-BB=9.B3E-2J/S%2/Q]W0
M>-R?&N(`0Q0C>;.>GMS"1T2W1K)(BJHXV:CS*)6#J(Z@,$S4SEIA,F;YGI1D
MG`:+=O0AE&MXW2,E>?Q2IKJ_VHF=B`PV#OFX[(K#Y12/'6E/D(3#>9Q(>BE`
MC5-K1+ODMW<<*T:A;^:W+$"WZ&;.>^1'&QVTK/3/MN^0*TJ>38Z)@)/3+!V9
MHXOV=$JG\_9TQG<766]\'HV/LU;PA@6MP5LZG;6G=WS'%'#.`\I889RU;"-F
MOL1GA@\U_@YIM$?<@V9ENPG3.#3FWV?_S*+94^&Z8+*@X=;'`K$#,?B1B5]0
M2P,$%`````@`DP"$0E_6G=I,````8P```!T```!E>'!R97-S:6]N+61A=&%T
M>7!E<RUF86EL+G1X="O+STQ12,O/U\C,*U&HT%%(R\E/+%&HU.3EJN;EXJQ0
ML%6H4-!6,+7FY:KEY2H#*<Y-S,S3`+$@:A3`&H'R4*TEUE"QRFA#@UB0/@!0
M2P,$%`````@`^4Z$0NB"V<AY````PP````8```!F86-T+F-M3D$*PS`,NQO\
M!QV3PB@][)3N,86E$.@R2--B*/O[[&9LE_E@)"'+2KE"`A-34C0[V^*9#B8`
MQDI<MZ6&QF<XP7C#X(%3.:=9H'+XJ'%9XS^#H-,G<AE\"RRQ;B7_?KS,W:L'
M76^EF/9GNN,QI>P,?9N)AEWM@.D-4$L#!!0````(`.`$A$(\=0M]40```&P`
M```7````9G5N8RUN;RUP87)A;7,M9F%I;"YT>'0KR\],44C+S]?(S"M1J-!1
M2,O)3RQ1J-3DY:KFY>*L4+!5J%#05C"UYN6JY>4J`RG.3<S,TP"Q(&H4P!J!
M\E"M)=90L<IH0X-8L#C0=$V0`0!02P,$%`````@`8`6$0I8?+LE4````<```
M`"8```!F=6YC+7=R;VYG+7!A<F%M971E<BUD871A='EP92UF86EL+G1X="O+
MSTQ12,O/U\C,*U&HT%%(R\E/+%&HU.3EJN;EXJQ0L%6H4-!6,+7FY:KEY2H#
M*<Y-S,S3`+$@:A3`&H'R4*TEUE"QRFA#@UBP.-!TH,D5FB!#`%!+`P04````
M"``A3X1"8()+::L```!D`0``!0```&=C9"YC55#!#H,@#+V3\`\]HG'1'79B
M?LRBN)`H)H"[+/[[>%1F[*6OY;W74NLB.2V%37E)F=%[&!7R9'V(#0$&,ZQN
MK*3X2D&46]Z$;8Z:ZXD44ZCOJ:MRLP03J6<_%I@YF$*".#_1\YQ#E_A;8+5C
MK6/>C6TK732PO@J8V3`Q"8XAK/`F;MZ=O]GAT=9)5[<XR&>U(RTOZQ00+D#,
M0`^45+@TZ-ZQWP+\`(9ZE^('4$L#!!0````(`"9/A$+8L%B5H0```.0````&
M````9V-D:2YC-4Z[#L(P#-SS%;>15D#9JPX=8.(GJB8MD9JX2N,(A/AWX@JF
M.]OW<%/C%LGC3FQL0-VHID:/-=(<!X]$6&V<*'I<>5R<.6P*0+_,%%UZ[(*1
M_,K)8A[-60*4"TD&:"%\A$"NU!MN@L[H.EPJ1)LX!G!;\NRRV?^B&'4^\HF;
M7.=*KN6AWRA6AB>#+$4?I3(Y`S^XH(7M':7LV>[P$G=1?0%02P,$%`````@`
M'42$0NW)C#9*`0``'@,```D```!I;G!U="YT>'2-44%N@S`0/!>)/\P14M)`
MJJB'-(>^`W&P4I*L`CARW,91Q=^[M@,!VDKEXO4L.[,S7LR`-YR4W"M10TN<
M2K63JL:YK,JM)MG@+)4&GP)9&@8/C-=EHR&4$M<GS!9A$`;$@,F7Q=J7U[4%
M/R6]HZ:FDEM$L+C(B\05E;SXXD#[`^(P^(*[TMH=QA]'I@$,-GC!'"O,\(P%
MH@R/6,6,+%W?*T2""1.8V&'$,ZS1SXN<;\6PQ1R9G[\<J"H1$5[=-K'%`+O0
M#I'(J>"&N:&^X1G)\W7?D4%>'VT/6B6R.K?_7$>5^D,USEK;AV0C_BVA726%
M[K8:1^2S&1F=.IEGW=:W43U8V*[;)T>)TQBTM;-X'%JTUY_&74";$?74MS5^
M]UH+:B);.4O>4?<NZ?1!LK1_#N.%J!>ZR_AD78@F21,>^A>C'V#:^`_.]AM0
M2P,$%`````@`F*J$0E+J3I>>````_P````H```!I;G!U=#$N='AT58_-"L(P
M$(3OA;[#'!,]2)+&B^B+A!P$JRYH"J5J?^B[NYO:@X&P,\/N?@FE#GWP\5`6
MQ'((^U6.7!=U;1J5JRZ+J2P`B+L%)ZWL/G=ZU,KCQ.-5Q`96YWR:<VGK[M4F
MILB>/@Q![ACY:%DP"^;=T`7/,R4EZH]#"V0()N((:U;KQ&;@#LXOJ<<6CKWE
M1QC6JI)`<_)KR%_10@6$^P502P,$%`````@`QK%Q.'T_#3_0````R`$```T`
M``!J=FUN=6UT97-T,2YCC9#)"L(P%$7W@O]PEVV-=')7_`'!K1OIHFVJ+=AT
MT1GQWWUY#0Z(XB:Y(>?='-+7I<3)*E6+3D!OO8VKZV!WV$-U50-/P!<(!$*!
M#1QWN0!S0Z33@"TZ..CY=(5>Y_LQFO-(Q("UX6_+!8-/;C+<Q$W$867:B&6\
MUXYG=DQFQ_08_VF9<5-&W0E9IL<@_A"51D`2E$5?+',#Y011RRJ,WQ0?FE52
M*DLGV[S!7S%&,++U"6U1-FB*NKM(I#E\)$I"U2V\%^]I^C$2/$9\'B&%.U!+
M`P04````"`#L27(X1N7;JF<```""````#0```&IV;6YU;71E<W0R+F,KR\],
M44C3R,PK44C45*C6UU(HSL@OS4E1R$@L2U7P"O-55C#0,=0QTC%62$U,SE!(
M+%)(R4Q+2RU*!>HH3LXO2%70TN?E4E"H5@";88V%45M;R\L%1+Q<92#;<A,S
M\S1`+*!]0%$`4$L#!!0````(`+JS<3@B##[$00```$T````-````:G9M;G5M
M=&5S=#,N8RO+STQ12-,H`U*:"M7Z6@I>8;X*R@H&"HEY*0J&"EKZO%P*"IEY
M)0H5UF"JTIJ7JY:7BY<+I$,A-S$S#Z87*`H`4$L#!!0````(`&^LA$(I;1!:
M-P```%,````-````;6%I;F9I<G-T+G1X="O+STQ1R$W,S-,H`[(T>;FJ>;D4
M,O-*%"JM@8Q*!5L%4R"CEI<+)*V0EI^/KJX"I*X"H8Z7"P!02P,$%`````@`
M,Z^$0AMF)A!9````B0````D```!N97-T960Q+F/+S"M12-/(!)(5.@H@JA)"
M56DJ\')5\W(I@'F)UB!6-9B=!&1S5H-8R=8P^10PJQ9$5"C8*A@I:"L8(X2*
M4DM*B_+`A@#YO%QE^9DI"KF)F7D:()8FV)Y:`%!+`P04````"`"2M'$X#]+"
M%%L```"4````"0```&YE<W1E9#(N8SV-2PJ`,`Q$UQ9ZAUFV>(3B8?H3LK!N
MQ$WP[B9&A4QFYA$(C0,Y>7?NU+`&DEHBV#N`H1M05I-E-C/8TM<$3TJZD*EC
M0<.,*BJB_)]=%AZ3)?,^WC*-H"FRP!M02P,$%`````@`KF)E.+'O_8U&````
M:`````4```!O:S$N8\O,*U&HM.;E*LO/3%%(TP!1F@K5M;Q<F4")"FL(G:8!
MYFGR<E7S<BDH*(!X1:G%I3DEUF`^A*U@JV`(XY>4%N4AE`"-`P!02P,$%```
M``@`4+"$0I/O#?$=````(`````4```!O:S(N8RO+STQ1R$W,S-,H`[(T%:IY
MN104K,&`EZN6EPL`4$L#!!0``````(M0A$)V9+CN'@```!X````%````;VLS
M+F-V;VED(&UA:6XH=F]I9"D@>PT*("`R*S,[#0I]#0I02P,$%`````@`[ZB$
M0NM]*M\P````00```#````!P87)A;65T97(M;&]C86PM9&5L8V%R871I;VXM
M<V-O<&4M8V%L<V@M9F%I;"YT>'0KR\],44C+S]?(S"M1J-#DY:KFY5(`LZUY
MN6IYN<I`\KF)F7D:(!94'J3>5!.B``!02P,$%`````@`&&)E.&<]9A&,````
MX`````8```!P<F]C+F-%CL$.@R`01.\D^P]S5'I0S]1_Z"^02B))71L*E<;X
M[P6E=B\S^S*[F4;>W'PW0W`&B_7C'#PT?_#43D_&&R<;$B3>LQWP"E.534UB
M)8$TECU8[1(5#A;1HU6'7T;[,*@8UQY=6Y?$6O27CKBD+W_&B7%B76$;B>TL
M,6G+9XL]WLC,<L^\Y9*U*A<DOE!+`P04````"`"SK(1"9%!W.3$````W````
M!P```')E="YT>'0KR\],4<A-S,S3*`.R-'FYJGFY%#+S2A0JK8&,2@5;!5,0
MHRBUI+0H#RQ8R\O%RP4`4$L#!!0````(``BS<3C8A3;=J````)@!```'````
M<V-O<&4N8X60W0Z",`R%[TGV#N<2T01_+A<?9IM;6()@E,`"X=U=-P3%1"^Z
M-6V_]N38JD''D6=XJ/JF4>I6E]@CRUEB?<]QEK"DK>T%)J6"V($^N<&PI@X0
MIM%WF$`CS"E.F<(9`EM('RY4!M`;9^37_>.T(?;[0(QK3/S!XJ&%>0E:4Z>9
M^N3@Y2ZRE8]H5%=859`/,9$S/DXRQ\FPJ[!52MD/KVCFS2[G.,*")U!+`P04
M````"`#'L'$XFG_,PDL```!6````!P```'-E<G(Q+F/3UU(H2DU)3<Y)+$HL
MR<S/4\A/4\A+S$U5J%#(S%,HR4A5*`;QBI/S"U(5M/1YN3+S2A0JK!$T+U=9
M?F:*0FYB9IX&B*597<O+!0!02P,$%`````@`&;%Q.(\]GX91````6@````<`
M``!S97)R,BYCT]=2*$I-24W.22Q*+,G,SU/(3U/(2\Q-5:A0R,Q3*,E(52@&
M\8J3\PM2%;3T>;DR\TH4*JRA=+2A02R0S<M5EI^9HI";F)FG`6)I5M?R<@$`
M4$L#!!0````(``6Q<3@ZO*3/4````&$````'````<V5R<C,N8SW(00J`(!!&
MX;W@'?YEN>D`G6;0B09R)E1"B.X>$K1ZO&\)*)PX'E2HB2EL@U)F=(BB[8PZ
MKD8[&6'Q3K2AK]YY=YDD]&EDQOW\E$GTTX$O4$L#!!0````(`$*Q<3C9$OHK
M3P```&L````'````<V5R<C0N8UW*P0J`(!"$X;O@.\RQO/A,BZZTD+NATB5Z
M][!NG8;_8V)`X\QIIT9#3&$%2I51((JQ,?JLGNQ@A.B==Z=)1EGFK+CN2:+C
M)^^IDNBG$Q]02P,$%`````@`6;%Q.`H"'-!1````8@````<```!S97)R-2YC
M/8E+"H`@$(;W0G?XE^JF`W2:P48:R#%40I#NWF/1[GO,'H57#CL5:I(5.4(I
M,3I$T39&?:V&?##\/)G)G%E61"O:T!T&/EAP_2^1J'W)C2?>4$L#!!0````(
M`&6S<3ALM,Z85P```',````'````<V5R<C8N8]/74BA*34E-SDDL2BS)S,]3
MR$]3R$O,356H4,C,4RC)2%4H!O&*D_,+4A6T]'FY>+G*\C-3%-(T0)2F0C50
M68E"HC6446$-HVH5:N&*<Q,S\R#JJX&"`%!+`P04````"`!@N7$X'%@"R#T`
M```_````!P```'-E<G(W+F/+S"M1J+#FY>+E*LO/3%'(3<S,TP"Q-!6J];44
M*A4RBQ5*\U)2DW,2BU)3%+3T>;D4%"H4;!4J@7IJ>;D`4$L#!!0````(`+6T
M<3@>S;R7.@```#\````'````<V5R<C@N8\O,*U&HM.;EXN4JR\],4<A-S,S3
M`+$T%:KUM10J%#*+%4KS4E*3<Q*+4E,4M/1YN12`HK9@/;6\7`!02P,$%```
M``@`W;1Q.'U9GFQ'````3@````<```!S97)R.2YCR\PK4:BTYN7BY2K+STQ1
MR$W,S-,`L305JO6U%"H4,HL5\O)+%!+S%!*+BA(K%;3T>;D4%#*!NBJL0:R*
M:*-8!5NP$;6\7`!02P,$%`````@`^+1Q.(,>^&53````6@````@```!S97)R
M,3`N8\O,*U&HM.;EXN4JR\],4<A-S,S3`+$T%:KUM10J%#*+%?+R2Q02\Q3R
MBS+S$HLJ%<H2BS(3DW)2%;3T>;D4%#*!!E1$&QK$6H-X%0JV8.-J>;D`4$L#
M!!0````(`!"U<3@^$0@22@```$\````(````<V5R<C$Q+F/+S"M1J+3FY>+E
M*LO/3%'(3<S,TP"Q-!6J];44*A4RBQ7R\DL4$A722O.22S+S\Q2T]'FY%!0R
M@?HJK$&L"@5;A4H-32"[EI<+`%!+`P04````"`#TL(1"?36M@5T```!X````
M"````'-E<G(Q,BYC-8RQ"H`P#`7W0O_AC=K%R4G\F(@M!#2%6$41_]U&<#NX
MXU@*KL$[[[A2:H[,<XO;.T!CV5705_M88`HKL?Q1%Y#`&R07D"#KS$)ZX2!E
MFI:(T-G'QN=@E#!^5'<O4$L#!!0````(`&VU<3AVB"0D20```$X````(````
M<V5R<C$S+F/+S"M1J+3FY>+E*LO/3%'(3<S,TP"Q-!6J];44*A4RBQ7R\DL4
M$O,4$HN*$BL5M/1YN104,H&Z*JQ!K`H%6X7*:*-8(*>6EPL`4$L#!!0````(
M`'NV<3@6T6$G/0```$8````(````<V5R<C$T+F,KR\],44C3*`-2F@K5M;Q<
MO%P@MD)N8F8>3%1?2R%=(;-8H30O)34Y)[$H-45!2Y^72T$A74/3FI<+J`D`
M4$L#!!0````(`+.V<3A7I'HM*0```"P````(````<V5R<C$U+F/3UU+(RU?(
M3<S,4]#2Y^7*S"M1J+#FY>+E*LO/3%%(TP!1F@K5M2`A`%!+`P04````"`#O
MMG$X\2J/*3T```!E````"````'-E<G(Q-BYCT]=2R$W,S%/(RR]1R$DL+E'0
MTN?ERLPK4:BPYN7BY2K+STQ12-,`49H*U;4@(9!D)4(2I!M%'BR:CB($`%!+
M`P04````"``LMW$X&P?6NU0```!_````"````'-E<G(Q-RYCR\PK4:BPYN7B
MY2K+STQ12-,`49H*U0H5"K8*E=:U"OI:"I4*F<4*I<6I*0I)J6GY1:D**:G)
M.0I:^B!=F4#]E0C]Z6CZ%6KA4KF)F7DP6;`H"`(`4$L#!!0````(``:X<3@\
MN@+`6@```&T````(````<V5R<C$X+F/3UU+(+<TIR2S(254H3LU-S"O)3%9(
M+2K*+RI6T-+GY<K,*U&HL.;E*LO/3%%(TP!1F@K5O%P*"I4*MF`9!84*("M1
M01N"(2+11K%`02,#,"]=0Q-(U_)R`0!02P,$%`````@`&KEQ.$P--NE.````
M70````@```!S97)R,3DN8]/74D@L*DJL+%9(S$M1*$LLRDQ,RDDM5DA.S,O+
M+U%(2E7(3U,HJ2Q(52C+STQ1T-+GY0(S*JRAC,IH0X-8&"<W,3-/`\325*BN
MY>4"`%!+`P04````"``WL81"XQDB4\H````P`0``"````'-E<G(R,"YC38[-
M:L,P$(3/U5/,K99QZQQ*H1@?<DA.?0EC*:[`TAI%*VQ"W[TKXT!/^S>S\[4U
MKI$\OHF-#5B&R>+CZ[-N55OCC"72%`>/1%ALO%'TN/`X._-Z5P#.\T31I9]=
M,))?.%E,HWF'/'`AP05959F<T>JA7J)-'`-.G?I5^UVTJ$K##4K)(H.[H<KH
M>YPT#@=W$F?GNWTNQ%CEAM^XS776Y2J\QUBL#$\&N7!(5`&`'UQXHNQA:[>7
M3=PK^H-5=]C^#_*Y9*W-I@OU'U!+`P04````"`!*4H1"I3>H>*D!``!N!```
M!P```'-S;W)T+F-]D\UNPC`,Q^^5^@X^4BH$'%'IDTP]1#2EKFA2I>E@FGCW
M.7&_,C;"@<1Q[)_M?_?;7AO;@U`@C!%?4`HK`.G47Z0J45U!FU*:[3Z.X@B5
MA58\LFGOG#^.AR*#]=IO.92NX'@`>9.M5+;?[5"5\@$'L+49X.0BNAB8\7^3
M@0_OO7AOV\ZG^M180F?(5&V<O==E4R5Q]!U'S_F^%:@V;L<7Q(&0PR'S6X*F
MPXD/S;+=;V]:=V`U&"E*AT3&>XTW"1N$<^X>)N"M'),645&`)CV.L6F-;'23
MS#;?&RS(E<M@J\O=P`Z.LP5S`DW)`*X4,CRYAPX('!VW?E5/0%X;/5QK8M;$
M[/O^O@K@Z'JPTLSAF81;3TDPP&6Z,:U_7)$CL#/-V-;2/<5V:)=88_8FS,YK
M8D"E7AAX804;W[^F@#-WDN&*)'2<UHS>9*&#O/5RN1W%%;KP2-+52&`>0HBX
M=*"_B\X7?AF,(75/*H<[VOKOCK!LUK6$4AF-DP_^NGY1$JY&LP"'<_U?-IHU
M^U8KL!+]J/`195$YYI@NC:.O<>*HZ(F^&M$R!_]^`%!+`P04````"`!=2X1"
M.&UYEI````#P````!0```'-U;2YC14]!#L(@$+R3\(<YMO1`/7C"OL(7$*TM
MB8"A14E,_VX74+/)[NS,[FQ6BG.T,&X=IS$LZ+'.(<()R1EG.XVD2,7%1[<6
MJ-VB2'UZ<X75QC6$6L[>G`%(&-"K#/?)?T/\42'CG%ZSN8]HLC-.`U);^&+S
M6Z?<U?M?I>P,M78X%&6KYA0;S4GA;W@$/P5MRTL?4$L#!!0````(`-0$A$+#
MN,HA40```&H````4````=F%R+6%S+69U;F,M9F%I;"YT>'0KR\],44C+S]?(
MS"M1J-!12,O)3RQ1J-3DY:KFY>*L4+!5J%#05C"UYN6JY>4J`RG.3<S,TP"Q
M(&H4P!J!\E"M)=90L<IH0X-8$*="0Q.D'0!02P,$%`````@`<$N$0GA@>P^%
M````Q0````<```!A<FET:"YC74T[#@(A$.U)N,,K%;,A43MBL84G\`3$)3H%
MK%E8`S'>W1FTLI@W[S.39\VX4+G'4.B*<WTL(6>:4X9/$T;FMQ1#*K@47X(P
M8[72BMBJ#K+:=^4U.DF>,TV(GM)&V%:KEU8`*DX\`_8.73?6#3L<?IK?V1$<
M^IUD1_<7F8Z6*WL@=6^!#U!+`P04````"`!1N(-";!'9[S(````T````$P``
M`&%R<F%Y+6EN9&5X+6)A9"YT>'0KR\],4<A-S,S3*`.R-'FYJGFY%#+S2A0J
MHPT-8JV!G,IH$SW36`5;!3,@KY:7BY<+`%!+`P04````"`!HO8-"?QU(.3L`
M``!#````)@```&%R<F%Y+6EN9&5X+6-O;7!L97@M97AP<F5S<VEO;BUB860N
M='AT*\O/3%'(3<S,TR@#LC1YN:IYN10R\TH4*JRAC,IH0X-8$*<RND)+PTC/
M2-M(,U;!5L$,*%;+R\7+!0!02P$"%``4````"`!+O8-"G48^0SD```!!````
M)0`````````!`"``````````87)R87DM:6YD97@M8V]M<&QE>"UE>'!R97-S
M:6]N+6]K+G1X=%!+`0(4`!0````(`"^O@T+BWIU_,````#(````2````````
M``$`(````'P```!A<G)A>2UI;F1E>"UO:RYT>'102P$"%``4````"`"6N(-"
M7/!=P#@```!$````%@`````````!`"````#<````87)R87DM:6YD97@M=F%R
M+6]K+G1X=%!+`0(4`!0````(`"X`A$*N'%RX3@```&`````?``````````$`
M(````$@!``!A<W-I9VYM96YT+61A=&%T>7!E<RTR+69A:6PN='AT4$L!`A0`
M%`````@`=+^#0G`^CS4Z````10```!T``````````0`@````TP$``&%S<VEG
M;FUE;G0M9&%T871Y<&5S+69A:6PN='AT4$L!`A0`%`````@`[$Z$0G1X.Z$R
M`P``>0@```<``````````0`@````2`(``&)S;W)T+F-02P$"%``4````"`"3
M`(1"7]:=VDP```!C````'0`````````!`"````"?!0``97AP<F5S<VEO;BUD
M871A='EP97,M9F%I;"YT>'102P$"%``4````"`#Y3H1"Z(+9R'D```##````
M!@`````````!`"`````F!@``9F%C="YC4$L!`A0`%`````@`X`2$0CQU"WU1
M````;````!<``````````0`@````PP8``&9U;F,M;F\M<&%R86US+69A:6PN
M='AT4$L!`A0`%`````@`8`6$0I8?+LE4````<````"8``````````0`@````
M20<``&9U;F,M=W)O;F<M<&%R86UE=&5R+61A=&%T>7!E+69A:6PN='AT4$L!
M`A0`%`````@`(4^$0F""2VFK````9`$```4``````````0`@````X0<``&=C
M9"YC4$L!`A0`%`````@`)D^$0MBP6)6A````Y`````8``````````0`@````
MKP@``&=C9&DN8U!+`0(4`!0````(`!U$A$+MR8PV2@$``!X#```)````````
M``$`(````'0)``!I;G!U="YT>'102P$"%``4````"`"8JH1"4NI.EYX```#_
M````"@`````````!`"````#E"@``:6YP=70Q+G1X=%!+`0(4`!0````(`,:Q
M<3A]/PT_T````,@!```-``````````$`(````*L+``!J=FUN=6UT97-T,2YC
M4$L!`A0`%`````@`[$ER.$;EVZIG````@@````T``````````0`@````I@P`
M`&IV;6YU;71E<W0R+F-02P$"%``4````"`"ZLW$X(@P^Q$$```!-````#0``
M```````!`"`````X#0``:G9M;G5M=&5S=#,N8U!+`0(4`!0````(`&^LA$(I
M;1!:-P```%,````-``````````$`(````*0-``!M86EN9FER<W0N='AT4$L!
M`A0`%`````@`,Z^$0AMF)A!9````B0````D``````````0`@````!@X``&YE
M<W1E9#$N8U!+`0(4`!0````(`)*T<3@/TL(46P```)0````)``````````$`
M(````(8.``!N97-T960R+F-02P$"%``4````"`"N8F4XL>_]C48```!H````
M!0`````````!`"`````(#P``;VLQ+F-02P$"%``4````"`!0L(1"D^\-\1T`
M```@````!0`````````!`"````!Q#P``;VLR+F-02P$"%``4``````"+4(1"
M=F2X[AX````>````!0`````````!`"````"Q#P``;VLS+F-02P$"%``4````
M"`#OJ(1"ZWTJWS````!!````,``````````!`"````#R#P``<&%R86UE=&5R
M+6QO8V%L+61E;&-A<F%T:6]N+7-C;W!E+6-A;'-H+69A:6PN='AT4$L!`A0`
M%`````@`&&)E.&<]9A&,````X`````8``````````0`@````<!```'!R;V,N
M8U!+`0(4`!0````(`+.LA$)D4'<Y,0```#<````'``````````$`(````"`1
M``!R970N='AT4$L!`A0`%`````@`"+-Q.-B%-MVH````F`$```<`````````
M`0`@````=A$``'-C;W!E+F-02P$"%``4````"`#'L'$XFG_,PDL```!6````
M!P`````````!`"````!#$@``<V5R<C$N8U!+`0(4`!0````(`!FQ<3B//9^&
M40```%H````'``````````$`(````+,2``!S97)R,BYC4$L!`A0`%`````@`
M!;%Q.#J\I,]0````80````<``````````0`@````*1,``'-E<G(S+F-02P$"
M%``4````"`!"L7$XV1+Z*T\```!K````!P`````````!`"````">$P``<V5R
M<C0N8U!+`0(4`!0````(`%FQ<3@*`AS040```&(````'``````````$`(```
M`!(4``!S97)R-2YC4$L!`A0`%`````@`9;-Q.&RTSIA7````<P````<`````
M`````0`@````B!0``'-E<G(V+F-02P$"%``4````"`!@N7$X'%@"R#T````_
M````!P`````````!`"`````$%0``<V5R<C<N8U!+`0(4`!0````(`+6T<3@>
MS;R7.@```#\````'``````````$`(````&85``!S97)R."YC4$L!`A0`%```
M``@`W;1Q.'U9GFQ'````3@````<``````````0`@````Q14``'-E<G(Y+F-0
M2P$"%``4````"`#XM'$X@Q[X95,```!:````"``````````!`"`````Q%@``
M<V5R<C$P+F-02P$"%``4````"``0M7$X/A$($DH```!/````"``````````!
M`"````"J%@``<V5R<C$Q+F-02P$"%``4````"`#TL(1"?36M@5T```!X````
M"``````````!`"`````:%P``<V5R<C$R+F-02P$"%``4````"`!MM7$X=H@D
M)$D```!.````"``````````!`"````"=%P``<V5R<C$S+F-02P$"%``4````
M"`![MG$X%M%A)ST```!&````"``````````!`"`````,&```<V5R<C$T+F-0
M2P$"%``4````"`"SMG$X5Z1Z+2D````L````"``````````!`"````!O&```
M<V5R<C$U+F-02P$"%``4````"`#OMG$X\2J/*3T```!E````"``````````!
M`"````"^&```<V5R<C$V+F-02P$"%``4````"``LMW$X&P?6NU0```!_````
M"``````````!`"`````A&0``<V5R<C$W+F-02P$"%``4````"``&N'$X/+H"
MP%H```!M````"``````````!`"````";&0``<V5R<C$X+F-02P$"%``4````
M"``:N7$X3`TVZ4X```!=````"``````````!`"`````;&@``<V5R<C$Y+F-0
M2P$"%``4````"``WL81"XQDB4\H````P`0``"``````````!`"````"/&@``
M<V5R<C(P+F-02P$"%``4````"`!*4H1"I3>H>*D!``!N!```!P`````````!
M`"````!_&P``<W-O<G0N8U!+`0(4`!0````(`%U+A$(X;7F6D````/`````%
M``````````$`(````$T=``!S=6TN8U!+`0(4`!0````(`-0$A$+#N,HA40``
M`&H````4``````````$`(``````>``!V87(M87,M9G5N8RUF86EL+G1X=%!+
M`0(4`!0````(`'!+A$)X8'L/A0```,4````'``````````$`(````(,>``!A
M<FET:"YC4$L!`A0`%`````@`4;B#0FP1V>\R````-````!,``````````0`@
M````+1\``&%R<F%Y+6EN9&5X+6)A9"YT>'102P$"%``4````"`!HO8-"?QU(
M.3L```!#````)@`````````!`"````"0'P``87)R87DM:6YD97@M8V]M<&QE
J>"UE>'!R97-S:6]N+6)A9"YT>'102P4&`````#4`-0`D#```#R``````
`
end
SHAR_EOF
  (set 20 13 04 04 23 03 48 'TestFiles.zip'; eval "$shar_touch") &&
  chmod 0644 'TestFiles.zip'
if test $? -ne 0
then ${echo} 'restore of TestFiles.zip failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'TestFiles.zip: MD5 check failed'
       ) << \SHAR_EOF
4a276dc538618513b56ca2e77387ca38  TestFiles.zip
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'TestFiles.zip'` -ne 11337 && \
  ${echo} 'restoration warning:  size of TestFiles.zip is not 11337'
  fi
fi
# ============= Token.java ==============
if test -f 'Token.java' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING Token.java (file already exists)'
else
${echo} 'x - extracting Token.java (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 Token.java
M+RH)0T]0-#8R,"`M(%!R;VIE8W0@,PT*("H)4W1E<&AE;B!297!P97(-"B`J
M+PT*#0IP=6)L:6,@8VQA<W,@5&]K96X@>PT*#0H)4W1R:6YG('1O:V5N(#T@
M;G5L;#L-"@E3=')I;F<@='EP92`](&YU;&P[#0H)"0T*"7!U8FQI8R!4;VME
M;B@I#0H)>PT*"7T-"@D)#0H)<'5B;&EC(%1O:V5N*%-T<FEN9R!T;VLL(%-T
M<FEN9R!T>7`I#0H)>PT*"0ET;VME;B`]('1O:SL-"@D)='EP92`]('1Y<#L-
M"@E]#0H)"0T*"7!U8FQI8R!3=')I;F<@9V5T5&]K96XH*0T*"7L-"@D)<F5T
M=7)N('1O:V5N.PT*"7T-"@D-"@EP=6)L:6,@4W1R:6YG(&=E=%1Y<&4H*0T*
9"7L-"@D)<F5T=7)N('1Y<&4[#0H)?0T*?6,@
`
end
SHAR_EOF
  (set 20 13 04 04 21 10 59 'Token.java'; eval "$shar_touch") &&
  chmod 0644 'Token.java'
if test $? -ne 0
then ${echo} 'restore of Token.java failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'Token.java: MD5 check failed'
       ) << \SHAR_EOF
ec7b4c8f164c7f990eedffa061fc34b6  Token.java
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'Token.java'` -ne 340 && \
  ${echo} 'restoration warning:  size of Token.java is not 340'
  fi
fi
# ============= VarElement.java ==============
if test -f 'VarElement.java' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING VarElement.java (file already exists)'
else
${echo} 'x - extracting VarElement.java (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 VarElement.java
M+RH)0T]0-#8R,"`M(%!R;VIE8W0@,PT*("H)4W1E<&AE;B!297!P97(-"B`J
M+PT*#0IP=6)L:6,@8VQA<W,@5F%R16QE;65N="!E>'1E;F1S($5L96UE;G0-
M"GL-"@EP=6)L:6,@5F%R16QE;65N="A%;&5M96YT(&4I#0H)>PT*"0EN86UE
M(#T@92YG971.86UE*"D[#0H)"71Y<&4@/2!E+F=E=%1Y<&4H*3L-"@E]#0H)
M#0H)<'5B;&EC(%9A<D5L96UE;G0@8VQO;F4H*0T*"7L-"@D)5F%R16QE;65N
M="!V(#T@;F5W(%9A<D5L96UE;G0H=&AI<RD[#0H)"7)E='5R;B!V.PT*"7T-
$"GT-"CT@
`
end
SHAR_EOF
  (set 20 13 04 04 21 11 34 'VarElement.java'; eval "$shar_touch") &&
  chmod 0644 'VarElement.java'
if test $? -ne 0
then ${echo} 'restore of VarElement.java failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'VarElement.java: MD5 check failed'
       ) << \SHAR_EOF
680f1a7330b29673697fcebd82c8ef8f  VarElement.java
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'VarElement.java'` -ne 274 && \
  ${echo} 'restoration warning:  size of VarElement.java is not 274'
  fi
fi
if rm -fr ${lock_dir}
then ${echo} 'x - removed lock directory `'${lock_dir}\''.'
else ${echo} 'x - failed to remove lock directory `'${lock_dir}\''.'
  exit 1
fi
exit 0
